; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_MVENUSAUR  ; 4
	const DEX_CHARMANDER ; 5
	const DEX_CHARMELEON ; 6
	const DEX_CHARIZARD  ; 7
	const DEX_MCHARZARDX ; 8
	const DEX_MCHARZARDY ; 9
	const DEX_SQUIRTLE   ; 10
	const DEX_WARTORTLE  ; 11
	const DEX_BLASTOISE  ; 12
	const DEX_MBLASTOISE ; 13
	const DEX_CATERPIE   ; 14
	const DEX_METAPOD    ; 15
	const DEX_BUTTERFREE ; 16
	const DEX_WEEDLE     ; 17
	const DEX_KAKUNA     ; 18
	const DEX_BEEDRILL   ; 19
	const DEX_MBEEDRILL  ; 20
	const DEX_PIDGEY     ; 21
	const DEX_PIDGEOTTO  ; 22
	const DEX_PIDGEOT    ; 23
	const DEX_MPIDGEOT   ; 24
	const DEX_RATTATA    ; 25
	const DEX_RATICATE   ; 26
	const DEX_SPEAROW    ; 27
	const DEX_FEAROW     ; 28
	const DEX_EKANS      ; 29
	const DEX_ARBOK      ; 30
	const DEX_PICHU      ; 31
	const DEX_PIKACHU    ; 32
	const DEX_RAICHU     ; 33
	const DEX_MRAICHUX   ; 34
	const DEX_MRAICHUY   ; 35
	const DEX_SANDSHREW  ; 36
	const DEX_SANDSLASH  ; 37
	const DEX_NIDORAN_F  ; 38
	const DEX_NIDORINA   ; 39
	const DEX_NIDOQUEEN  ; 40
	const DEX_NIDORAN_M  ; 41
	const DEX_NIDORINO   ; 42
	const DEX_NIDOKING   ; 43
	const DEX_CLEFFA     ; 44
	const DEX_CLEFAIRY   ; 45
	const DEX_CLEFABLE   ; 46
	const DEX_MCLEFABLE  ; 47
	const DEX_VULPIX     ; 48
	const DEX_NINETALES  ; 49
	const DEX_IGGLYBUFF  ; 50
	const DEX_JIGGLYPUFF ; 51
	const DEX_WIGGLYTUFF ; 52
	const DEX_ZUBAT      ; 53
	const DEX_GOLBAT     ; 54
	const DEX_CROBAT     ; 55
	const DEX_ODDISH     ; 56
	const DEX_GLOOM      ; 57
	const DEX_VILEPLUME  ; 58
	const DEX_BELLOSSOM  ; 59
	const DEX_PARAS      ; 60
	const DEX_PARASECT   ; 61
	const DEX_VENONAT    ; 62
	const DEX_VENOMOTH   ; 63
	const DEX_DIGLETT    ; 64
	const DEX_DUGTRIO    ; 65
	const DEX_MEOWTH     ; 66
	const DEX_PERSIAN    ; 67
	const DEX_PSYDUCK    ; 68
	const DEX_GOLDUCK    ; 69
	const DEX_MANKEY     ; 70
	const DEX_PRIMEAPE   ; 71
	const DEX_ANNIHILAPE ; 72
	const DEX_GROWLITHE  ; 73
	const DEX_ARCANINE   ; 74
	const DEX_POLIWAG    ; 75
	const DEX_POLIWHIRL  ; 76
	const DEX_POLIWRATH  ; 77
	const DEX_POLITOED   ; 78
	const DEX_ABRA       ; 79
	const DEX_KADABRA    ; 80
	const DEX_ALAKAZAM   ; 81
	const DEX_MALAKAZAM  ; 82
	const DEX_MACHOP     ; 83
	const DEX_MACHOKE    ; 84
	const DEX_MACHAMP    ; 85
	const DEX_BELLSPROUT ; 86
	const DEX_WEEPINBELL ; 87
	const DEX_VICTREEBEL ; 88
	const DEX_MVICTREBEL ; 89
	const DEX_TENTACOOL  ; 90
	const DEX_TENTACRUEL ; 91
	const DEX_GEODUDE    ; 92
	const DEX_GRAVELER   ; 93
	const DEX_GOLEM      ; 94
	const DEX_PONYTA     ; 95
	const DEX_RAPIDASH   ; 96
	const DEX_SLOWPOKE   ; 97
	const DEX_SLOWBRO    ; 98
	const DEX_MSLOWBRO   ; 99
	const DEX_SLOWKING   ; 100
	const DEX_MAGNEMITE  ; 101
	const DEX_MAGNETON   ; 102
	const DEX_MAGNEZONE  ; 103
	const DEX_FARFETCHD  ; 104
	const DEX_DODUO      ; 105
	const DEX_DODRIO     ; 106
	const DEX_SEEL       ; 107
	const DEX_DEWGONG    ; 108
	const DEX_GRIMER     ; 109
	const DEX_MUK        ; 110
	const DEX_SHELLDER   ; 111
	const DEX_CLOYSTER   ; 112
	const DEX_GASTLY     ; 113
	const DEX_HAUNTER    ; 114
	const DEX_GENGAR     ; 115
	const DEX_MGENGAR    ; 116
	const DEX_ONIX       ; 117
	const DEX_STEELIX    ; 118
	const DEX_MSTEELIX   ; 119
	const DEX_DROWZEE    ; 120
	const DEX_HYPNO      ; 121
	const DEX_KRABBY     ; 122
	const DEX_KINGLER    ; 123
	const DEX_VOLTORB    ; 124
	const DEX_ELECTRODE  ; 125
	const DEX_EXEGGCUTE  ; 126
	const DEX_EXEGGUTOR  ; 127
	const DEX_CUBONE     ; 128
	const DEX_MAROWAK    ; 129
	const DEX_TYROGUE    ; 130
	const DEX_HITMONLEE  ; 131
	const DEX_HITMONCHAN ; 132
	const DEX_HITMONTOP  ; 133
	const DEX_LICKITUNG  ; 134
	const DEX_LICKILICKY ; 135
	const DEX_KOFFING    ; 136
	const DEX_WEEZING    ; 137
	const DEX_RHYHORN    ; 138
	const DEX_RHYDON     ; 139
	const DEX_RHYPERIOR  ; 140
	const DEX_HAPPINY    ; 141
	const DEX_CHANSEY    ; 142
	const DEX_BLISSEY    ; 143
	const DEX_TANGELA    ; 144
	const DEX_TANGROWTH  ; 145
	const DEX_KANGASKHAN ; 146
	const DEX_MKANGASKAN ; 147
	const DEX_HORSEA     ; 148
	const DEX_SEADRA     ; 149
	const DEX_KINGDRA    ; 150
	const DEX_GOLDEEN    ; 151
	const DEX_SEAKING    ; 152
	const DEX_STARYU     ; 153
	const DEX_STARMIE    ; 154
	const DEX_MSTARMIE   ; 155
	const DEX_MIME_JR    ; 156
	const DEX_MR_MIME    ; 157
	const DEX_SCYTHER    ; 158
	const DEX_SCIZOR     ; 159
	const DEX_MSCIZOR    ; 160
	const DEX_KLEAVOR    ; 161
	const DEX_SMOOCHUM   ; 162
	const DEX_JYNX       ; 163
	const DEX_ELEKID     ; 164
	const DEX_ELECTABUZZ ; 165
	const DEX_ELECTIVIRE ; 166
	const DEX_MAGBY      ; 167
	const DEX_MAGMAR     ; 168
	const DEX_MAGMORTAR  ; 169
	const DEX_PINSIR     ; 170
	const DEX_MPINSIR    ; 171
	const DEX_TAUROS     ; 172
	const DEX_MAGIKARP   ; 173
	const DEX_GYARADOS   ; 174
	const DEX_MGYARADOS  ; 175
	const DEX_LAPRAS     ; 176
	const DEX_DITTO      ; 177
	const DEX_EEVEE      ; 178
	const DEX_VAPOREON   ; 179
	const DEX_JOLTEON    ; 180
	const DEX_FLAREON    ; 181
	const DEX_ESPEON     ; 182
	const DEX_UMBREON    ; 183
	const DEX_LEAFEON    ; 184
	const DEX_GLACEON    ; 185
	const DEX_SYLVEON    ; 186
	const DEX_PORYGON    ; 187
	const DEX_PORYGON2   ; 188
	const DEX_PORYGONZ   ; 189
	const DEX_OMANYTE    ; 190
	const DEX_OMASTAR    ; 191
	const DEX_KABUTO     ; 192
	const DEX_KABUTOPS   ; 193
	const DEX_AERODACTYL ; 194
	const DEX_MARODACTYL ; 195
	const DEX_MUNCHLAX   ; 196
	const DEX_SNORLAX    ; 197
	const DEX_ARTICUNO   ; 198
	const DEX_ZAPDOS     ; 199
	const DEX_MOLTRES    ; 200
	const DEX_DRATINI    ; 201
	const DEX_DRAGONAIR  ; 202
	const DEX_DRAGONITE  ; 203
	const DEX_MDRAGONITE ; 204
	const DEX_ARM_MEWTWO ; 205
	const DEX_MEWTWO     ; 206
	const DEX_MMEWTWOX   ; 207
	const DEX_MMEWTWOY   ; 208
	const DEX_MEW        ; 209
	const DEX_MELTAN     ; 210
	const DEX_MELMETAL   ; 211
	const DEX_VENUSTOISE ; 212
	const DEX_THU_FI_ZER ; 213
	const DEX_MZYGARDE   ; 214
	const DEX_UNECROZMA  ; 215
	const DEX_MRAYQUAZA  ; 216
	const DEX_EETERNATUS ; 217
	const DEX_ARCEUS     ; 218
	const DEX_MISSINGNO  ; 219
	const DEX_BLUESDAD   ; 220
	const DEX_BLUESMOM   ; 221
	const DEX_DAD        ; 222

DEF NUM_POKEMON EQU const_value - 1
