; pokemon ids
; indexes for:
; - MonsterNames (see data/pokemon/names.asm)
; - EvosMovesPointerTable (see data/pokemon/evos_moves.asm)
; - CryData (see data/pokemon/cries.asm)
; - PokedexOrder (see data/pokemon/dex_order.asm)
; - PokedexEntryPointers (see data/pokemon/dex_entries.asm)
	const_def
	const NO_MON             ; $00
	const BULBASAUR          ; 1
	const IVYSAUR            ; 2
	const VENUSAUR           ; 3
	const MVENUSAUR          ; 4
	const CHARMANDER         ; 5
	const CHARMELEON         ; 6
	const CHARIZARD          ; 7
	const MCHARZARDX         ; 8
	const MCHARZARDY         ; 9
	const SQUIRTLE           ; 10
	const WARTORTLE          ; 11
	const BLASTOISE          ; 12
	const MBLASTOISE         ; 13
	const CATERPIE           ; 14
	const METAPOD            ; 15
	const BUTTERFREE         ; 16
	const WEEDLE             ; 17
	const KAKUNA             ; 18
	const BEEDRILL           ; 19
	const MBEEDRILL          ; 20
	const PIDGEY             ; 21
	const PIDGEOTTO          ; 22
	const PIDGEOT            ; 23
	const MPIDGEOT           ; 24
	const RATTATA            ; 25
	const RATICATE           ; 26
	const SPEAROW            ; 27
	const FEAROW             ; 28
	const EKANS              ; 29
	const ARBOK              ; 30
	const PICHU              ; 31
	const PIKACHU            ; 32
	const RAICHU             ; 33
	const SANDSHREW          ; 34
	const SANDSLASH          ; 35
	const NIDORAN_F          ; 36
	const NIDORINA           ; 37
	const NIDOQUEEN          ; 38
	const NIDORAN_M          ; 39
	const NIDORINO           ; 40
	const NIDOKING           ; 41
	const CLEFFA             ; 42
	const CLEFAIRY           ; 43
	const CLEFABLE           ; 44
	const VULPIX             ; 45
	const NINETALES          ; 46
	const IGGLYBUFF          ; 47
	const JIGGLYPUFF         ; 48
	const WIGGLYTUFF         ; 49
	const ZUBAT              ; 50
	const GOLBAT             ; 51
	const CROBAT             ; 52
	const ODDISH             ; 53
	const GLOOM              ; 54
	const VILEPLUME          ; 55
	const BELLOSSOM          ; 56
	const PARAS              ; 57
	const PARASECT           ; 58
	const VENONAT            ; 59
	const VENOMOTH           ; 60
	const DIGLETT            ; 61
	const DUGTRIO            ; 62
	const MEOWTH             ; 63
	const PERSIAN            ; 64
	const PSYDUCK            ; 65
	const GOLDUCK            ; 66
	const MANKEY             ; 67
	const PRIMEAPE           ; 68
	const ANNIHILAPE         ; 69
	const GROWLITHE          ; 70
	const ARCANINE           ; 71
	const POLIWAG            ; 72
	const POLIWHIRL          ; 73
	const POLIWRATH          ; 74
	const POLITOED           ; 75
	const ABRA               ; 76
	const KADABRA            ; 77
	const ALAKAZAM           ; 78
	const MALAKAZAM          ; 79
	const MACHOP             ; 80
	const MACHOKE            ; 81
	const MACHAMP            ; 82
	const BELLSPROUT         ; 83
	const WEEPINBELL         ; 84
	const VICTREEBEL         ; 85
	const TENTACOOL          ; 86
	const TENTACRUEL         ; 87
	const GEODUDE            ; 88
	const GRAVELER           ; 89
	const GOLEM              ; 90
	const PONYTA             ; 91
	const RAPIDASH           ; 92
	const SLOWPOKE           ; 93
	const SLOWBRO            ; 94
	const MSLOWBRO           ; 95
	const SLOWKING           ; 96
	const MAGNEMITE          ; 97
	const MAGNETON           ; 98
	const MAGNEZONE          ; 99
	const FARFETCHD          ; 100
	const DODUO              ; 101
	const DODRIO             ; 102
	const SEEL               ; 103
	const DEWGONG            ; 104
	const GRIMER             ; 105
	const MUK                ; 106
	const SHELLDER           ; 107
	const CLOYSTER           ; 108
	const GASTLY             ; 109
	const HAUNTER            ; 110
	const GENGAR             ; 111
	const MGENGAR            ; 112
	const ONIX               ; 113
	const STEELIX            ; 114
	const MSTEELIX           ; 115
	const DROWZEE            ; 116
	const HYPNO              ; 117
	const KRABBY             ; 118
	const KINGLER            ; 119
	const VOLTORB            ; 120
	const ELECTRODE          ; 121
	const EXEGGCUTE          ; 122
	const EXEGGUTOR          ; 123
	const CUBONE             ; 124
	const MAROWAK            ; 125
	const TYROGUE            ; 126
	const HITMONLEE          ; 127
	const HITMONCHAN         ; 128
	const HITMONTOP          ; 129
	const LICKITUNG          ; 130
	const LICKILICKY         ; 131
	const KOFFING            ; 132
	const WEEZING            ; 133
	const RHYHORN            ; 134
	const RHYDON             ; 135
	const RHYPERIOR          ; 136
	const HAPPINY            ; 137
	const CHANSEY            ; 138
	const BLISSEY            ; 139
	const TANGELA            ; 140
	const KANGASKHAN         ; 141
	const HORSEA             ; 142
	const SEADRA             ; 143
	const GOLDEEN            ; 144
	const SEAKING            ; 145
	const STARYU             ; 146
	const STARMIE            ; 147
	const MR_MIME            ; 148
	const SCYTHER            ; 149
	const JYNX               ; 150
	const ELECTABUZZ         ; 151
	const MAGMAR             ; 152
	const PINSIR             ; 153
	const TAUROS             ; 154
	const MAGIKARP           ; 155
	const GYARADOS           ; 156
	const LAPRAS             ; 157
	const DITTO              ; 158
	const EEVEE              ; 159
	const VAPOREON           ; 160
	const JOLTEON            ; 161
	const FLAREON            ; 162
	const PORYGON            ; 163
	const OMANYTE            ; 164
	const OMASTAR            ; 165
	const KABUTO             ; 166
	const KABUTOPS           ; 167
	const AERODACTYL         ; 168
	const SNORLAX            ; 169
	const ARTICUNO           ; 170
	const ZAPDOS             ; 171
	const MOLTRES            ; 172
	const DRATINI            ; 173
	const DRAGONAIR          ; 174
	const DRAGONITE          ; 175
	const MEWTWO             ; 176
	const MEW                ; 177
	const ARCEUS             ; 178
	const FOSSIL_KABUTOPS    ; 179
	const FOSSIL_AERODACTYL  ; 180
	const MON_GHOST          ; 181

DEF NUM_POKEMON_INDEXES EQU const_value - 1

; player starter
DEF STARTER_PIKACHU EQU PIKACHU

; rival starters
DEF RIVAL_STARTER_JOLTEON  EQU 1
DEF RIVAL_STARTER_FLAREON  EQU 2
DEF RIVAL_STARTER_VAPOREON EQU 3

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
