; pokemon ids
; indexes for:
; - MonsterNames (see data/pokemon/names.asm)
; - EvosMovesPointerTable (see data/pokemon/evos_moves.asm)
; - CryData (see data/pokemon/cries.asm)
; - PokedexOrder (see data/pokemon/dex_order.asm)
; - PokedexEntryPointers (see data/pokemon/dex_entries.asm)
	const_def
	const NO_MON             ; $00
	const BULBASAUR          ; 1
	const IVYSAUR            ; 2
	const VENUSAUR           ; 3
	const MVENUSAUR          ; 4
	const CHARMANDER         ; 5
	const CHARMELEON         ; 6
	const CHARIZARD          ; 7
	const MCHARZARDX         ; 8
	const MCHARZARDY         ; 9
	const SQUIRTLE           ; 10
	const WARTORTLE          ; 11
	const BLASTOISE          ; 12
	const MBLASTOISE         ; 13
	const CATERPIE           ; 14
	const METAPOD            ; 15
	const BUTTERFREE         ; 16
	const WEEDLE             ; 17
	const KAKUNA             ; 18
	const BEEDRILL           ; 19
	const MBEEDRILL          ; 20
	const PIDGEY             ; 21
	const PIDGEOTTO          ; 22
	const PIDGEOT            ; 23
	const MPIDGEOT           ; 24
	const RATTATA            ; 25
	const RATICATE           ; 26
	const SPEAROW            ; 27
	const FEAROW             ; 28
	const EKANS              ; 29
	const ARBOK              ; 30
	const PICHU              ; 31
	const PIKACHU            ; 32
	const RAICHU             ; 33
	const SANDSHREW          ; 34
	const SANDSLASH          ; 35
	const NIDORAN_F          ; 36
	const NIDORINA           ; 37
	const NIDOQUEEN          ; 38
	const NIDORAN_M          ; 39
	const NIDORINO           ; 40
	const NIDOKING           ; 41
	const CLEFFA             ; 42
	const CLEFAIRY           ; 43
	const CLEFABLE           ; 44
	const VULPIX             ; 45
	const NINETALES          ; 46
	const IGGLYBUFF          ; 47
	const JIGGLYPUFF         ; 48
	const WIGGLYTUFF         ; 49
	const ZUBAT              ; 50
	const GOLBAT             ; 51
	const CROBAT             ; 52
	const ODDISH             ; 53
	const GLOOM              ; 54
	const VILEPLUME          ; 55
	const BELLOSSOM          ; 56
	const PARAS              ; 57
	const PARASECT           ; 58
	const VENONAT            ; 59
	const VENOMOTH           ; 60
	const DIGLETT            ; 61
	const DUGTRIO            ; 62
	const MEOWTH             ; 63
	const PERSIAN            ; 64
	const PSYDUCK            ; 65
	const GOLDUCK            ; 66
	const MANKEY             ; 67
	const PRIMEAPE           ; 68
	const ANNIHILAPE         ; 69
	const GROWLITHE          ; 70
	const ARCANINE           ; 71
	const POLIWAG            ; 72
	const POLIWHIRL          ; 73
	const POLIWRATH          ; 74
	const ABRA               ; 75
	const KADABRA            ; 76
	const ALAKAZAM           ; 77
	const MACHOP             ; 78
	const MACHOKE            ; 79
	const MACHAMP            ; 80
	const BELLSPROUT         ; 81
	const WEEPINBELL         ; 82
	const VICTREEBEL         ; 83
	const TENTACOOL          ; 84
	const TENTACRUEL         ; 85
	const GEODUDE            ; 86
	const GRAVELER           ; 87
	const GOLEM              ; 88
	const PONYTA             ; 89
	const RAPIDASH           ; 90
	const SLOWPOKE           ; 91
	const SLOWBRO            ; 92
	const MAGNEMITE          ; 93
	const MAGNETON           ; 94
	const FARFETCHD          ; 95
	const DODUO              ; 96
	const DODRIO             ; 97
	const SEEL               ; 98
	const DEWGONG            ; 99
	const GRIMER             ; 100
	const MUK                ; 101
	const SHELLDER           ; 102
	const CLOYSTER           ; 103
	const GASTLY             ; 104
	const HAUNTER            ; 105
	const GENGAR             ; 106
	const ONIX               ; 107
	const DROWZEE            ; 108
	const HYPNO              ; 109
	const KRABBY             ; 110
	const KINGLER            ; 111
	const VOLTORB            ; 112
	const ELECTRODE          ; 113
	const EXEGGCUTE          ; 114
	const EXEGGUTOR          ; 115
	const CUBONE             ; 116
	const MAROWAK            ; 117
	const HITMONLEE          ; 118
	const HITMONCHAN         ; 119
	const LICKITUNG          ; 120
	const KOFFING            ; 121
	const WEEZING            ; 122
	const RHYHORN            ; 123
	const RHYDON             ; 124
	const CHANSEY            ; 125
	const TANGELA            ; 126
	const KANGASKHAN         ; 127
	const HORSEA             ; 128
	const SEADRA             ; 129
	const GOLDEEN            ; 130
	const SEAKING            ; 131
	const STARYU             ; 132
	const STARMIE            ; 133
	const MR_MIME            ; 134
	const SCYTHER            ; 135
	const JYNX               ; 136
	const ELECTABUZZ         ; 137
	const MAGMAR             ; 138
	const PINSIR             ; 139
	const TAUROS             ; 140
	const MAGIKARP           ; 141
	const GYARADOS           ; 142
	const LAPRAS             ; 143
	const DITTO              ; 144
	const EEVEE              ; 145
	const VAPOREON           ; 146
	const JOLTEON            ; 147
	const FLAREON            ; 148
	const PORYGON            ; 149
	const OMANYTE            ; 150
	const OMASTAR            ; 151
	const KABUTO             ; 152
	const KABUTOPS           ; 153
	const AERODACTYL         ; 154
	const SNORLAX            ; 155
	const ARTICUNO           ; 156
	const ZAPDOS             ; 157
	const MOLTRES            ; 158
	const DRATINI            ; 159
	const DRAGONAIR          ; 160
	const DRAGONITE          ; 161
	const MEWTWO             ; 162
	const MEW                ; 163
	const ARCEUS             ; 164
	const FOSSIL_KABUTOPS    ; 165
	const FOSSIL_AERODACTYL  ; 166
	const MON_GHOST          ; 167

DEF NUM_POKEMON_INDEXES EQU const_value - 1

; player starter
DEF STARTER_PIKACHU EQU PIKACHU

; rival starters
DEF RIVAL_STARTER_JOLTEON  EQU 1
DEF RIVAL_STARTER_FLAREON  EQU 2
DEF RIVAL_STARTER_VAPOREON EQU 3

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
