; pokemon ids
; indexes for:
; - MonsterNames (see data/pokemon/names.asm)
; - EvosMovesPointerTable (see data/pokemon/evos_moves.asm)
; - CryData (see data/pokemon/cries.asm)
; - PokedexOrder (see data/pokemon/dex_order.asm)
; - PokedexEntryPointers (see data/pokemon/dex_entries.asm)
	const_def
	const NO_MON             ; $00
	const BULBASAUR          ; 1
	const IVYSAUR            ; 2
	const VENUSAUR           ; 3
	const MVENUSAUR          ; 4
	const CHARMANDER         ; 5
	const CHARMELEON         ; 6
	const CHARIZARD          ; 7
	const MCHARZARDX         ; 8
	const MCHARZARDY         ; 9
	const SQUIRTLE           ; 10
	const WARTORTLE          ; 11
	const BLASTOISE          ; 12
	const MBLASTOISE         ; 13
	const CATERPIE           ; 14
	const METAPOD            ; 15
	const BUTTERFREE         ; 16
	const WEEDLE             ; 17
	const KAKUNA             ; 18
	const BEEDRILL           ; 19
	const MBEEDRILL          ; 20
	const PIDGEY             ; 21
	const PIDGEOTTO          ; 22
	const PIDGEOT            ; 23
	const RATTATA            ; 24
	const RATICATE           ; 25
	const SPEAROW            ; 26
	const FEAROW             ; 27
	const EKANS              ; 28
	const ARBOK              ; 29
	const PIKACHU            ; 30
	const RAICHU             ; 31
	const SANDSHREW          ; 32
	const SANDSLASH          ; 33
	const NIDORAN_F          ; 34
	const NIDORINA           ; 35
	const NIDOQUEEN          ; 36
	const NIDORAN_M          ; 37
	const NIDORINO           ; 38
	const NIDOKING           ; 39
	const CLEFAIRY           ; 40
	const CLEFABLE           ; 41
	const VULPIX             ; 42
	const NINETALES          ; 43
	const JIGGLYPUFF         ; 44
	const WIGGLYTUFF         ; 45
	const ZUBAT              ; 46
	const GOLBAT             ; 47
	const ODDISH             ; 48
	const GLOOM              ; 49
	const VILEPLUME          ; 50
	const PARAS              ; 51
	const PARASECT           ; 52
	const VENONAT            ; 53
	const VENOMOTH           ; 54
	const DIGLETT            ; 55
	const DUGTRIO            ; 56
	const MEOWTH             ; 57
	const PERSIAN            ; 58
	const PSYDUCK            ; 59
	const GOLDUCK            ; 60
	const MANKEY             ; 61
	const PRIMEAPE           ; 62
	const GROWLITHE          ; 63
	const ARCANINE           ; 64
	const POLIWAG            ; 65
	const POLIWHIRL          ; 66
	const POLIWRATH          ; 67
	const ABRA               ; 68
	const KADABRA            ; 69
	const ALAKAZAM           ; 70
	const MACHOP             ; 71
	const MACHOKE            ; 72
	const MACHAMP            ; 73
	const BELLSPROUT         ; 74
	const WEEPINBELL         ; 75
	const VICTREEBEL         ; 76
	const TENTACOOL          ; 77
	const TENTACRUEL         ; 78
	const GEODUDE            ; 79
	const GRAVELER           ; 80
	const GOLEM              ; 81
	const PONYTA             ; 82
	const RAPIDASH           ; 83
	const SLOWPOKE           ; 84
	const SLOWBRO            ; 85
	const MAGNEMITE          ; 86
	const MAGNETON           ; 87
	const FARFETCHD          ; 88
	const DODUO              ; 89
	const DODRIO             ; 90
	const SEEL               ; 91
	const DEWGONG            ; 92
	const GRIMER             ; 93
	const MUK                ; 94
	const SHELLDER           ; 95
	const CLOYSTER           ; 96
	const GASTLY             ; 97
	const HAUNTER            ; 98
	const GENGAR             ; 99
	const ONIX               ; 100
	const DROWZEE            ; 101
	const HYPNO              ; 102
	const KRABBY             ; 103
	const KINGLER            ; 104
	const VOLTORB            ; 105
	const ELECTRODE          ; 106
	const EXEGGCUTE          ; 107
	const EXEGGUTOR          ; 108
	const CUBONE             ; 109
	const MAROWAK            ; 110
	const HITMONLEE          ; 111
	const HITMONCHAN         ; 112
	const LICKITUNG          ; 113
	const KOFFING            ; 114
	const WEEZING            ; 115
	const RHYHORN            ; 116
	const RHYDON             ; 117
	const CHANSEY            ; 118
	const TANGELA            ; 119
	const KANGASKHAN         ; 120
	const HORSEA             ; 121
	const SEADRA             ; 122
	const GOLDEEN            ; 123
	const SEAKING            ; 124
	const STARYU             ; 125
	const STARMIE            ; 126
	const MR_MIME            ; 127
	const SCYTHER            ; 128
	const JYNX               ; 129
	const ELECTABUZZ         ; 130
	const MAGMAR             ; 131
	const PINSIR             ; 132
	const TAUROS             ; 133
	const MAGIKARP           ; 134
	const GYARADOS           ; 135
	const LAPRAS             ; 136
	const DITTO              ; 137
	const EEVEE              ; 138
	const VAPOREON           ; 139
	const JOLTEON            ; 140
	const FLAREON            ; 141
	const PORYGON            ; 142
	const OMANYTE            ; 143
	const OMASTAR            ; 144
	const KABUTO             ; 145
	const KABUTOPS           ; 146
	const AERODACTYL         ; 147
	const SNORLAX            ; 148
	const ARTICUNO           ; 149
	const ZAPDOS             ; 150
	const MOLTRES            ; 151
	const DRATINI            ; 152
	const DRAGONAIR          ; 153
	const DRAGONITE          ; 154
	const MEWTWO             ; 155
	const MEW                ; 156
	const ARCEUS             ; 157
	const FOSSIL_KABUTOPS    ; 158
	const FOSSIL_AERODACTYL  ; 159
	const MON_GHOST          ; 160

DEF NUM_POKEMON_INDEXES EQU const_value - 1

; player starter
DEF STARTER_PIKACHU EQU PIKACHU

; rival starters
DEF RIVAL_STARTER_JOLTEON  EQU 1
DEF RIVAL_STARTER_FLAREON  EQU 2
DEF RIVAL_STARTER_VAPOREON EQU 3

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
