; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_MVENUSAUR  ; 4
	const DEX_CHARMANDER ; 5
	const DEX_CHARMELEON ; 6
	const DEX_CHARIZARD  ; 7
	const DEX_MCHARZARDX ; 8
	const DEX_MCHARZARDY ; 9
	const DEX_SQUIRTLE   ; 10
	const DEX_WARTORTLE  ; 11
	const DEX_BLASTOISE  ; 12
	const DEX_MBLASTOISE ; 13
	const DEX_CATERPIE   ; 14
	const DEX_METAPOD    ; 15
	const DEX_BUTTERFREE ; 16
	const DEX_WEEDLE     ; 17
	const DEX_KAKUNA     ; 18
	const DEX_BEEDRILL   ; 19
	const DEX_MBEEDRILL  ; 20
	const DEX_PIDGEY     ; 21
	const DEX_PIDGEOTTO  ; 22
	const DEX_PIDGEOT    ; 23
	const DEX_RATTATA    ; 24
	const DEX_RATICATE   ; 25
	const DEX_SPEAROW    ; 26
	const DEX_FEAROW     ; 27
	const DEX_EKANS      ; 28
	const DEX_ARBOK      ; 29
	const DEX_PIKACHU    ; 30
	const DEX_RAICHU     ; 31
	const DEX_SANDSHREW  ; 32
	const DEX_SANDSLASH  ; 33
	const DEX_NIDORAN_F  ; 34
	const DEX_NIDORINA   ; 35
	const DEX_NIDOQUEEN  ; 36
	const DEX_NIDORAN_M  ; 37
	const DEX_NIDORINO   ; 38
	const DEX_NIDOKING   ; 39
	const DEX_CLEFAIRY   ; 40
	const DEX_CLEFABLE   ; 41
	const DEX_VULPIX     ; 42
	const DEX_NINETALES  ; 43
	const DEX_JIGGLYPUFF ; 44
	const DEX_WIGGLYTUFF ; 45
	const DEX_ZUBAT      ; 46
	const DEX_GOLBAT     ; 47
	const DEX_ODDISH     ; 48
	const DEX_GLOOM      ; 49
	const DEX_VILEPLUME  ; 50
	const DEX_PARAS      ; 51
	const DEX_PARASECT   ; 52
	const DEX_VENONAT    ; 53
	const DEX_VENOMOTH   ; 54
	const DEX_DIGLETT    ; 55
	const DEX_DUGTRIO    ; 56
	const DEX_MEOWTH     ; 57
	const DEX_PERSIAN    ; 58
	const DEX_PSYDUCK    ; 59
	const DEX_GOLDUCK    ; 60
	const DEX_MANKEY     ; 61
	const DEX_PRIMEAPE   ; 62
	const DEX_GROWLITHE  ; 63
	const DEX_ARCANINE   ; 64
	const DEX_POLIWAG    ; 65
	const DEX_POLIWHIRL  ; 66
	const DEX_POLIWRATH  ; 67
	const DEX_ABRA       ; 68
	const DEX_KADABRA    ; 69
	const DEX_ALAKAZAM   ; 70
	const DEX_MACHOP     ; 71
	const DEX_MACHOKE    ; 72
	const DEX_MACHAMP    ; 73
	const DEX_BELLSPROUT ; 74
	const DEX_WEEPINBELL ; 75
	const DEX_VICTREEBEL ; 76
	const DEX_TENTACOOL  ; 77
	const DEX_TENTACRUEL ; 78
	const DEX_GEODUDE    ; 79
	const DEX_GRAVELER   ; 80
	const DEX_GOLEM      ; 81
	const DEX_PONYTA     ; 82
	const DEX_RAPIDASH   ; 83
	const DEX_SLOWPOKE   ; 84
	const DEX_SLOWBRO    ; 85
	const DEX_MAGNEMITE  ; 86
	const DEX_MAGNETON   ; 87
	const DEX_FARFETCHD  ; 88
	const DEX_DODUO      ; 89
	const DEX_DODRIO     ; 90
	const DEX_SEEL       ; 91
	const DEX_DEWGONG    ; 92
	const DEX_GRIMER     ; 93
	const DEX_MUK        ; 94
	const DEX_SHELLDER   ; 95
	const DEX_CLOYSTER   ; 96
	const DEX_GASTLY     ; 97
	const DEX_HAUNTER    ; 98
	const DEX_GENGAR     ; 99
	const DEX_ONIX       ; 100
	const DEX_DROWZEE    ; 101
	const DEX_HYPNO      ; 102
	const DEX_KRABBY     ; 103
	const DEX_KINGLER    ; 104
	const DEX_VOLTORB    ; 105
	const DEX_ELECTRODE  ; 106
	const DEX_EXEGGCUTE  ; 107
	const DEX_EXEGGUTOR  ; 108
	const DEX_CUBONE     ; 109
	const DEX_MAROWAK    ; 110
	const DEX_HITMONLEE  ; 111
	const DEX_HITMONCHAN ; 112
	const DEX_LICKITUNG  ; 113
	const DEX_KOFFING    ; 114
	const DEX_WEEZING    ; 115
	const DEX_RHYHORN    ; 116
	const DEX_RHYDON     ; 117
	const DEX_CHANSEY    ; 118
	const DEX_TANGELA    ; 119
	const DEX_KANGASKHAN ; 120
	const DEX_HORSEA     ; 121
	const DEX_SEADRA     ; 122
	const DEX_GOLDEEN    ; 123
	const DEX_SEAKING    ; 124
	const DEX_STARYU     ; 125
	const DEX_STARMIE    ; 126
	const DEX_MR_MIME    ; 127
	const DEX_SCYTHER    ; 128
	const DEX_JYNX       ; 129
	const DEX_ELECTABUZZ ; 130
	const DEX_MAGMAR     ; 131
	const DEX_PINSIR     ; 132
	const DEX_TAUROS     ; 133
	const DEX_MAGIKARP   ; 134
	const DEX_GYARADOS   ; 135
	const DEX_LAPRAS     ; 136
	const DEX_DITTO      ; 137
	const DEX_EEVEE      ; 138
	const DEX_VAPOREON   ; 139
	const DEX_JOLTEON    ; 140
	const DEX_FLAREON    ; 141
	const DEX_PORYGON    ; 142
	const DEX_OMANYTE    ; 143
	const DEX_OMASTAR    ; 144
	const DEX_KABUTO     ; 145
	const DEX_KABUTOPS   ; 146
	const DEX_AERODACTYL ; 147
	const DEX_SNORLAX    ; 148
	const DEX_ARTICUNO   ; 149
	const DEX_ZAPDOS     ; 150
	const DEX_MOLTRES    ; 151
	const DEX_DRATINI    ; 152
	const DEX_DRAGONAIR  ; 153
	const DEX_DRAGONITE  ; 154
	const DEX_MEWTWO     ; 155
	const DEX_MEW        ; 156
	const DEX_ARCEUS     ; 157

DEF NUM_POKEMON EQU const_value - 1
