; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_MVENUSAUR  ; 4
	const DEX_CHARMANDER ; 5
	const DEX_CHARMELEON ; 6
	const DEX_CHARIZARD  ; 7
	const DEX_MCHARZARDX ; 8
	const DEX_MCHARZARDY ; 9
	const DEX_SQUIRTLE   ; 10
	const DEX_WARTORTLE  ; 11
	const DEX_BLASTOISE  ; 12
	const DEX_MBLASTOISE ; 13
	const DEX_CATERPIE   ; 14
	const DEX_METAPOD    ; 15
	const DEX_BUTTERFREE ; 16
	const DEX_WEEDLE     ; 17
	const DEX_KAKUNA     ; 18
	const DEX_BEEDRILL   ; 19
	const DEX_MBEEDRILL  ; 20
	const DEX_PIDGEY     ; 21
	const DEX_PIDGEOTTO  ; 22
	const DEX_PIDGEOT    ; 23
	const DEX_MPIDGEOT   ; 24
	const DEX_RATTATA    ; 25
	const DEX_RATICATE   ; 26
	const DEX_SPEAROW    ; 27
	const DEX_FEAROW     ; 28
	const DEX_EKANS      ; 29
	const DEX_ARBOK      ; 30
	const DEX_PICHU      ; 31
	const DEX_PIKACHU    ; 32
	const DEX_RAICHU     ; 33
	const DEX_SANDSHREW  ; 34
	const DEX_SANDSLASH  ; 35
	const DEX_NIDORAN_F  ; 36
	const DEX_NIDORINA   ; 37
	const DEX_NIDOQUEEN  ; 38
	const DEX_NIDORAN_M  ; 39
	const DEX_NIDORINO   ; 40
	const DEX_NIDOKING   ; 41
	const DEX_CLEFFA     ; 42
	const DEX_CLEFAIRY   ; 43
	const DEX_CLEFABLE   ; 44
	const DEX_VULPIX     ; 45
	const DEX_NINETALES  ; 46
	const DEX_IGGLYBUFF  ; 47
	const DEX_JIGGLYPUFF ; 48
	const DEX_WIGGLYTUFF ; 49
	const DEX_ZUBAT      ; 50
	const DEX_GOLBAT     ; 51
	const DEX_CROBAT     ; 52
	const DEX_ODDISH     ; 53
	const DEX_GLOOM      ; 54
	const DEX_VILEPLUME  ; 55
	const DEX_BELLOSSOM  ; 56
	const DEX_PARAS      ; 57
	const DEX_PARASECT   ; 58
	const DEX_VENONAT    ; 59
	const DEX_VENOMOTH   ; 60
	const DEX_DIGLETT    ; 61
	const DEX_DUGTRIO    ; 62
	const DEX_MEOWTH     ; 63
	const DEX_PERSIAN    ; 64
	const DEX_PSYDUCK    ; 65
	const DEX_GOLDUCK    ; 66
	const DEX_MANKEY     ; 67
	const DEX_PRIMEAPE   ; 68
	const DEX_ANNIHILAPE ; 69
	const DEX_GROWLITHE  ; 70
	const DEX_ARCANINE   ; 71
	const DEX_POLIWAG    ; 72
	const DEX_POLIWHIRL  ; 73
	const DEX_POLIWRATH  ; 74
	const DEX_POLITOED   ; 75
	const DEX_ABRA       ; 76
	const DEX_KADABRA    ; 77
	const DEX_ALAKAZAM   ; 78
	const DEX_MALAKAZAM  ; 79
	const DEX_MACHOP     ; 80
	const DEX_MACHOKE    ; 81
	const DEX_MACHAMP    ; 82
	const DEX_BELLSPROUT ; 83
	const DEX_WEEPINBELL ; 84
	const DEX_VICTREEBEL ; 85
	const DEX_TENTACOOL  ; 86
	const DEX_TENTACRUEL ; 87
	const DEX_GEODUDE    ; 88
	const DEX_GRAVELER   ; 89
	const DEX_GOLEM      ; 90
	const DEX_PONYTA     ; 91
	const DEX_RAPIDASH   ; 92
	const DEX_SLOWPOKE   ; 93
	const DEX_SLOWBRO    ; 94
	const DEX_MSLOWBRO   ; 95
	const DEX_SLOWKING   ; 96
	const DEX_MAGNEMITE  ; 97
	const DEX_MAGNETON   ; 98
	const DEX_MAGNEZONE  ; 99
	const DEX_FARFETCHD  ; 100
	const DEX_DODUO      ; 101
	const DEX_DODRIO     ; 102
	const DEX_SEEL       ; 103
	const DEX_DEWGONG    ; 104
	const DEX_GRIMER     ; 105
	const DEX_MUK        ; 106
	const DEX_SHELLDER   ; 107
	const DEX_CLOYSTER   ; 108
	const DEX_GASTLY     ; 109
	const DEX_HAUNTER    ; 110
	const DEX_GENGAR     ; 111
	const DEX_MGENGAR    ; 112
	const DEX_ONIX       ; 113
	const DEX_STEELIX    ; 114
	const DEX_MSTEELIX   ; 115
	const DEX_DROWZEE    ; 116
	const DEX_HYPNO      ; 117
	const DEX_KRABBY     ; 118
	const DEX_KINGLER    ; 119
	const DEX_VOLTORB    ; 120
	const DEX_ELECTRODE  ; 121
	const DEX_EXEGGCUTE  ; 122
	const DEX_EXEGGUTOR  ; 123
	const DEX_CUBONE     ; 124
	const DEX_MAROWAK    ; 125
	const DEX_TYROGUE    ; 126
	const DEX_HITMONLEE  ; 127
	const DEX_HITMONCHAN ; 128
	const DEX_HITMONTOP  ; 129
	const DEX_LICKITUNG  ; 130
	const DEX_LICKILICKY ; 131
	const DEX_KOFFING    ; 132
	const DEX_WEEZING    ; 133
	const DEX_RHYHORN    ; 134
	const DEX_RHYDON     ; 135
	const DEX_RHYPERIOR  ; 136
	const DEX_HAPPINY    ; 137
	const DEX_CHANSEY    ; 138
	const DEX_BLISSEY    ; 139
	const DEX_TANGELA    ; 140
	const DEX_TANGROWTH  ; 141
	const DEX_KANGASKHAN ; 142
	const DEX_MKANGASKAN ; 143
	const DEX_HORSEA     ; 144
	const DEX_SEADRA     ; 145
	const DEX_KINGDRA    ; 146
	const DEX_GOLDEEN    ; 147
	const DEX_SEAKING    ; 148
	const DEX_STARYU     ; 149
	const DEX_STARMIE    ; 150
	const DEX_MIME_JR    ; 151
	const DEX_MR_MIME    ; 152
	const DEX_SCYTHER    ; 153
	const DEX_SCIZOR     ; 154
	const DEX_MSCIZOR    ; 155
	const DEX_KLEAVOR    ; 156
	const DEX_SMOOCHUM   ; 157
	const DEX_JYNX       ; 158
	const DEX_ELEKID     ; 159
	const DEX_ELECTABUZZ ; 160
	const DEX_ELECTIVIRE ; 161
	const DEX_MAGBY      ; 162
	const DEX_MAGMAR     ; 163
	const DEX_MAGMORTAR  ; 164
	const DEX_PINSIR     ; 165
	const DEX_MPINSIR    ; 166
	const DEX_TAUROS     ; 167
	const DEX_MAGIKARP   ; 168
	const DEX_GYARADOS   ; 169
	const DEX_MGYARADOS  ; 170
	const DEX_LAPRAS     ; 171
	const DEX_DITTO      ; 172
	const DEX_EEVEE      ; 173
	const DEX_VAPOREON   ; 174
	const DEX_JOLTEON    ; 175
	const DEX_FLAREON    ; 176
	const DEX_ESPEON     ; 177
	const DEX_UMBREON    ; 178
	const DEX_LEAFEON    ; 179
	const DEX_GLACEON    ; 180
	const DEX_SYLVEON    ; 181
	const DEX_PORYGON    ; 182
	const DEX_PORYGON2   ; 183
	const DEX_PORYGONZ   ; 184
	const DEX_OMANYTE    ; 185
	const DEX_OMASTAR    ; 186
	const DEX_KABUTO     ; 187
	const DEX_KABUTOPS   ; 188
	const DEX_AERODACTYL ; 189
	const DEX_MARODACTYL ; 190
	const DEX_MUNCHLAX   ; 191
	const DEX_SNORLAX    ; 192
	const DEX_ARTICUNO   ; 193
	const DEX_ZAPDOS     ; 194
	const DEX_MOLTRES    ; 195
	const DEX_DRATINI    ; 196
	const DEX_DRAGONAIR  ; 197
	const DEX_DRAGONITE  ; 198
	const DEX_MEWTWO     ; 199
	const DEX_MMEWTWOX   ; 200
	const DEX_MMEWTWOY   ; 201
	const DEX_MEW        ; 202
	const DEX_VENUSTOISE ; 203
	const DEX_ZYGARDEC   ; 204
	const DEX_UNECROZMA  ; 205
	const DEX_MRAYQUAZA  ; 206
	const DEX_EETERNATUS ; 207
	const DEX_ARCEUS     ; 208
	const DEX_MISSINGNO  ; 209
	const DEX_BLUESDAD   ; 210
	const DEX_BLUESMOM   ; 211
	const DEX_DAD        ; 212

DEF NUM_POKEMON EQU const_value - 1
