FuchsiaBillsGrandpasHouse_Script:
	RPTextChooser FuchsiaBillsGrandpasHouse_TextPointers, FuchsiaBillsGrandpasHouse_TextPointers_Rocket
	call EnableAutoTextBoxDrawing
	ret

FuchsiaBillsGrandpasHouse_TextPointers:
	dw FuchsiaHouse1Text1
	dw FuchsiaHouse1Text2
	dw FuchsiaHouse1Text3

FuchsiaBillsGrandpasHouse_TextPointers_Rocket:
	dw GenericNPCText_RocketPath
	dw GenericNPCText_RocketPath
	dw GenericNPCText_RocketPath

FuchsiaHouse1Text1:
	text_far _FuchsiaHouse1Text1
	text_end

FuchsiaHouse1Text2:
	text_far _FuchsiaHouse1Text2
	text_end

FuchsiaHouse1Text3:
	text_far _FuchsiaHouse1Text3
	text_end
