SeviiSevenIslandGym2DiveCavern_Script:
	jp EnableAutoTextBoxDrawing

SeviiSevenIslandGym2DiveCavern_TextPointers:
	dw PickUpItemText

;SeviiSevenIslandGym2DiveCavernText1:
;	text_far _SeviiSevenIslandGym2DiveCavernText1
;	text_end
