SeviiTwoIslandPokemonCenter_Script:
	call Serial_TryEstablishingExternallyClockedConnection
	jp EnableAutoTextBoxDrawing

SeviiTwoIslandPokemonCenter_TextPointers:
	dw SeviiTwoIslandPokemonCenter_HealNurseText
	dw SeviiTwoIslandPokemonCenter_ChanseyText
	dw SeviiTwoIslandPokemonCenter_Text1
	dw SeviiTwoIslandPokemonCenter_Text2

SeviiTwoIslandPokemonCenter_HealNurseText:
	script_pokecenter_nurse

SeviiTwoIslandPokemonCenter_ChanseyText:
	text_asm
	callfar PokecenterChanseyText
	jp TextScriptEnd

SeviiTwoIslandPokemonCenter_Text1:
	text_far _SeviiTwoIslandPokemonCenter_Text1
	text_end

SeviiTwoIslandPokemonCenter_Text2:
	text_far _SeviiTwoIslandPokemonCenter_Text2
	text_end
