SeviiOneIslandPokemonCenterAndMart_Script:
	RPTextChooser SeviiOneIslandPokemonCenterAndMart_TextPointers, SeviiOneIslandPokemonCenterAndMart_TextPointers_Rocket
	call Serial_TryEstablishingExternallyClockedConnection
	jp EnableAutoTextBoxDrawing

SeviiOneIslandPokemonCenterAndMart_TextPointers:
	dw SeviiOneIslandPokemonCenterAndMart_HealNurseText
	dw SeviiOneIslandPokemonCenterAndMart_ChanseyText
	dw SeviiOneIslandPokemonCenterAndMart_Text1
	dw SeviiOneIslandPokemonCenterAndMart_Text2
	; from Mart
	dw SeviiOneIslandPokemonCenterAndMart_CashierText
	dw SeviiOneIslandPokemonCenterAndMart_CashierTMText
	dw SeviiOneIslandPokemonCenterAndMart_Text3
	dw SeviiOneIslandPokemonCenterAndMart_Text4

SeviiOneIslandPokemonCenterAndMart_TextPointers_Rocket:
	dw SeviiOneIslandPokemonCenterAndMart_HealNurseText
	dw SeviiOneIslandPokemonCenterAndMart_ChanseyText
	dw GenericNPCText_RocketPath
	dw GenericNPCText_RocketPath
	; from Mart
	dw SeviiOneIslandPokemonCenterAndMart_CashierText
	dw SeviiOneIslandPokemonCenterAndMart_CashierTMText
	dw GenericNPCText_RocketPath
	dw GenericNPCText_RocketPath

; Center

SeviiOneIslandPokemonCenterAndMart_HealNurseText:
	script_pokecenter_nurse

SeviiOneIslandPokemonCenterAndMart_ChanseyText:
	text_asm
	callfar PokecenterChanseyText
	jp TextScriptEnd

SeviiOneIslandPokemonCenterAndMart_Text1:
	text_far _SeviiOneIslandPokemonCenterAndMart_Text1
	text_end

SeviiOneIslandPokemonCenterAndMart_Text2:
	text_far _SeviiOneIslandPokemonCenterAndMart_Text2
	text_end

; Mart

SeviiOneIslandPokemonCenterAndMart_CashierText:
	script_mart GREAT_BALL, SUPER_POTION, REVIVE, ESCAPE_ROPE, SUPER_REPEL, ANTIDOTE, BURN_HEAL, ICE_HEAL, PARLYZ_HEAL

SeviiOneIslandPokemonCenterAndMart_CashierTMText:
    text_asm
	callfar TMMartClerkDialogue
    jp TextScriptEnd

SeviiOneIslandPokemonCenterAndMart_Text3:
	text_far _SeviiOneIslandPokemonCenterAndMart_Text3
	text_end

SeviiOneIslandPokemonCenterAndMart_Text4:
	text_far _SeviiOneIslandPokemonCenterAndMart_Text4
	text_end
