SeviiFiveIslandCityDive_Script:
	call EnableAutoTextBoxDrawing
	ld hl, SeviiFiveIslandCityDiveTrainerHeaders
	ld de, SeviiFiveIslandCityDive_ScriptPointers
	ld a, [wCurMapScript]
	call ExecuteCurMapScriptInTable
	ld [wCurMapScript], a
	ret

SeviiFiveIslandCityDive_TextPointers:
	dw SeviiFiveIslandCityDiveText1
	dw SeviiFiveIslandCityDiveText2
	dw SeviiFiveIslandCityDiveText3
	dw SeviiFiveIslandCityDiveText4

SeviiFiveIslandCityDive_ScriptPointers:
	dw CheckFightingMapTrainers
	dw DisplayEnemyTrainerTextAndStartBattle
	dw EndTrainerBattle

SeviiFiveIslandCityDiveTrainerHeaders:
	def_trainers
SeviiFiveIslandCityDiveTrainerHeader1:
	trainer EVENT_BEAT_SEVII_FIVE_ISLAND_CITY_DIVE_TRAINER_1, 3, SeviiFiveIslandCityDiveBattleText1, SeviiFiveIslandCityDiveEndBattleText1, SeviiFiveIslandCityDiveAfterBattleText1
SeviiFiveIslandCityDiveTrainerHeader2:
	trainer EVENT_BEAT_SEVII_FIVE_ISLAND_CITY_DIVE_TRAINER_2, 3, SeviiFiveIslandCityDiveBattleText2, SeviiFiveIslandCityDiveEndBattleText2, SeviiFiveIslandCityDiveAfterBattleText2
SeviiFiveIslandCityDiveTrainerHeader3:
	trainer EVENT_BEAT_SEVII_FIVE_ISLAND_CITY_DIVE_TRAINER_3, 3, SeviiFiveIslandCityDiveBattleText3, SeviiFiveIslandCityDiveEndBattleText3, SeviiFiveIslandCityDiveAfterBattleText3
SeviiFiveIslandCityDiveTrainerHeader4:
	trainer EVENT_BEAT_SEVII_FIVE_ISLAND_CITY_DIVE_TRAINER_4, 3, SeviiFiveIslandCityDiveBattleText4, SeviiFiveIslandCityDiveEndBattleText4, SeviiFiveIslandCityDiveAfterBattleText4
	db -1 ; end

SeviiFiveIslandCityDiveText1:
	text_asm
	ld hl, SeviiFiveIslandCityDiveTrainerHeader1
	jr SeviiFiveIslandCityDive_TalkToTrainer

SeviiFiveIslandCityDiveText2:
	text_asm
	ld hl, SeviiFiveIslandCityDiveTrainerHeader2
	jr SeviiFiveIslandCityDive_TalkToTrainer

SeviiFiveIslandCityDiveText3:
	text_asm
	ld hl, SeviiFiveIslandCityDiveTrainerHeader3
	jr SeviiFiveIslandCityDive_TalkToTrainer

SeviiFiveIslandCityDiveText4:
	text_asm
	ld hl, SeviiFiveIslandCityDiveTrainerHeader4
	jr SeviiFiveIslandCityDive_TalkToTrainer

SeviiFiveIslandCityDive_TalkToTrainer:
	call TalkToTrainer
	jp TextScriptEnd

SeviiFiveIslandCityDiveBattleText1:
	text_far _SeviiFiveIslandCityDiveBattleText1
	text_end

SeviiFiveIslandCityDiveEndBattleText1:
	text_far _SeviiFiveIslandCityDiveEndBattleText1
	text_end

SeviiFiveIslandCityDiveAfterBattleText1:
	text_far _SeviiFiveIslandCityDiveAfterBattleText1
	text_end

; ---

SeviiFiveIslandCityDiveBattleText2:
	text_far _SeviiFiveIslandCityDiveBattleText2
	text_end

SeviiFiveIslandCityDiveEndBattleText2:
	text_far _SeviiFiveIslandCityDiveEndBattleText2
	text_end

SeviiFiveIslandCityDiveAfterBattleText2:
	text_far _SeviiFiveIslandCityDiveAfterBattleText2
	text_end

; ---

SeviiFiveIslandCityDiveBattleText3:
	text_far _SeviiFiveIslandCityDiveBattleText3
	text_end

SeviiFiveIslandCityDiveEndBattleText3:
	text_far _SeviiFiveIslandCityDiveEndBattleText3
	text_end

SeviiFiveIslandCityDiveAfterBattleText3:
	text_far _SeviiFiveIslandCityDiveAfterBattleText3
	text_end

; ---

SeviiFiveIslandCityDiveBattleText4:
	text_far _SeviiFiveIslandCityDiveBattleText4
	text_end

SeviiFiveIslandCityDiveEndBattleText4:
	text_far _SeviiFiveIslandCityDiveEndBattleText4
	text_end

SeviiFiveIslandCityDiveAfterBattleText4:
	text_far _SeviiFiveIslandCityDiveAfterBattleText4
	text_end
