SeviiThreeIslandSecretGarden_Script:
	jp EnableAutoTextBoxDrawing

SeviiThreeIslandSecretGarden_TextPointers:
	dw PickUpItemText

;SeviiThreeIslandSecretGardenText1:
;	text_far _SeviiThreeIslandSecretGardenText1
;	text_end
