SECTION "Pics 1", ROMX

BulbasaurPicFront::   INCBIN "gfx/pokemon/front/bulbasaur.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/back/bulbasaurb.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/front/ivysaur.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/back/ivysaurb.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/front/venusaur.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/back/venusaurb.pic"
MVenusaurPicFront::   INCBIN "gfx/pokemon/front/mvenusaur.pic"
MVenusaurPicBack::    INCBIN "gfx/pokemon/back/mvenusaurb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/front/charmander.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/back/charmanderb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/front/charmeleon.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/back/charmeleonb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/front/charizard.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/back/charizardb.pic"
MCharzardXPicFront::  INCBIN "gfx/pokemon/front/mcharzardx.pic"
MCharzardXPicBack::   INCBIN "gfx/pokemon/back/mcharzardxb.pic"
MCharzardYPicFront::  INCBIN "gfx/pokemon/front/mcharzardy.pic"
MCharzardYPicBack::   INCBIN "gfx/pokemon/back/mcharzardyb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/front/squirtle.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/back/squirtleb.pic"
WartortlePicFront::   INCBIN "gfx/pokemon/front/wartortle.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/back/wartortleb.pic"
BlastoisePicFront::   INCBIN "gfx/pokemon/front/blastoise.pic"
BlastoisePicBack::    INCBIN "gfx/pokemon/back/blastoiseb.pic"
MBlastoisePicFront::  INCBIN "gfx/pokemon/front/mblastoise.pic"
MBlastoisePicBack::   INCBIN "gfx/pokemon/back/mblastoiseb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/front/caterpie.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/back/caterpieb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/front/metapod.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/back/metapodb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/front/butterfree.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/back/butterfreeb.pic"
WeedlePicFront::      INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack::       INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront::      INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack::       INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront::    INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack::     INCBIN "gfx/pokemon/back/beedrillb.pic"
MBeedrillPicFront::   INCBIN "gfx/pokemon/front/mbeedrill.pic"
MBeedrillPicBack::    INCBIN "gfx/pokemon/back/mbeedrillb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/front/pidgey.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/back/pidgeyb.pic"
PidgeottoPicFront::   INCBIN "gfx/pokemon/front/pidgeotto.pic"
PidgeottoPicBack::    INCBIN "gfx/pokemon/back/pidgeottob.pic"
PidgeotPicFront::     INCBIN "gfx/pokemon/front/pidgeot.pic"
PidgeotPicBack::      INCBIN "gfx/pokemon/back/pidgeotb.pic"
MPidgeotPicFront::    INCBIN "gfx/pokemon/front/mpidgeot.pic"
MPidgeotPicBack::     INCBIN "gfx/pokemon/back/mpidgeotb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/front/rattata.pic"
RattataPicBack::      INCBIN "gfx/pokemon/back/rattatab.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/front/raticate.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/back/raticateb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/front/spearow.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/back/spearowb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/front/fearow.pic"
FearowPicBack::       INCBIN "gfx/pokemon/back/fearowb.pic"
EkansPicFront::       INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack::        INCBIN "gfx/pokemon/back/ekansb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/front/arbok.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/back/arbokb.pic"


SECTION "Pics 2", ROMX

PichuPicFront::       INCBIN "gfx/pokemon/front/pichu.pic"
PichuPicBack::        INCBIN "gfx/pokemon/back/pichub.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/front/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/front/nidoranf.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/back/nidoranfb.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/front/nidorina.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/back/nidorinab.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/front/nidoqueen.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/back/nidoqueenb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/front/nidoranm.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/back/nidoranmb.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/front/nidorino.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/back/nidorinob.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/front/nidoking.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/back/nidokingb.pic"
CleffaPicFront::      INCBIN "gfx/pokemon/front/cleffa.pic"
CleffaPicBack::       INCBIN "gfx/pokemon/back/cleffab.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/front/clefairy.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/back/clefairyb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/front/clefable.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/back/clefableb.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/front/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/back/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/front/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
IgglybuffPicFront::   INCBIN "gfx/pokemon/front/igglybuff.pic"
IgglybuffPicBack::    INCBIN "gfx/pokemon/back/igglybuffb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/front/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/back/wigglytuffb.pic"
ZubatPicFront::       INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack::        INCBIN "gfx/pokemon/back/zubatb.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/front/golbat.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/back/golbatb.pic"
CrobatPicFront::      INCBIN "gfx/pokemon/front/crobat.pic"
CrobatPicBack::       INCBIN "gfx/pokemon/back/crobatb.pic"
OddishPicFront::      INCBIN "gfx/pokemon/front/oddish.pic"
OddishPicBack::       INCBIN "gfx/pokemon/back/oddishb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/front/gloom.pic"
GloomPicBack::        INCBIN "gfx/pokemon/back/gloomb.pic"
VileplumePicFront::   INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::    INCBIN "gfx/pokemon/back/vileplumeb.pic"
BellossomPicFront::   INCBIN "gfx/pokemon/front/bellossom.pic"
BellossomPicBack::    INCBIN "gfx/pokemon/back/bellossomb.pic"
ParasPicFront::       INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack::        INCBIN "gfx/pokemon/back/parasb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/front/parasect.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/back/parasectb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/front/venonat.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/back/venonatb.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/front/venomoth.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/back/venomothb.pic"


SECTION "Pics 3", ROMX

DiglettPicFront::     INCBIN "gfx/pokemon/front/diglett.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/back/diglettb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/front/dugtrio.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/back/dugtriob.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/front/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/front/persian.pic"
PersianPicBack::      INCBIN "gfx/pokemon/back/persianb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/front/psyduck.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/back/psyduckb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/front/golduck.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/back/golduckb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/front/mankey.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/back/mankeyb.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/front/primeape.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/back/primeapeb.pic"
AnnihilapePicFront::  INCBIN "gfx/pokemon/front/annihilape.pic"
AnnihilapePicBack::   INCBIN "gfx/pokemon/back/annihilapeb.pic"
GrowlithePicFront::   INCBIN "gfx/pokemon/front/growlithe.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/back/growlitheb.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/front/arcanine.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/back/arcanineb.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/front/poliwag.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/back/poliwagb.pic"
PoliwhirlPicFront::   INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack::    INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront::   INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack::    INCBIN "gfx/pokemon/back/poliwrathb.pic"
PolitoedPicFront::    INCBIN "gfx/pokemon/front/politoed.pic"
PolitoedPicBack::     INCBIN "gfx/pokemon/back/politoedb.pic"
AbraPicFront::        INCBIN "gfx/pokemon/front/abra.pic"
AbraPicBack::         INCBIN "gfx/pokemon/back/abrab.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/front/kadabra.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/back/kadabrab.pic"
AlakazamPicFront::    INCBIN "gfx/pokemon/front/alakazam.pic"
AlakazamPicBack::     INCBIN "gfx/pokemon/back/alakazamb.pic"
MAlakazamPicFront::   INCBIN "gfx/pokemon/front/malakazam.pic"
MAlakazamPicBack::    INCBIN "gfx/pokemon/back/malakazamb.pic"
MachopPicFront::      INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack::       INCBIN "gfx/pokemon/back/machopb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/front/machoke.pic"
MachokePicBack::      INCBIN "gfx/pokemon/back/machokeb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/front/machamp.pic"
MachampPicBack::      INCBIN "gfx/pokemon/back/machampb.pic"
BellsproutPicFront::  INCBIN "gfx/pokemon/front/bellsprout.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/back/bellsproutb.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/front/weepinbell.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/back/weepinbellb.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/front/victreebel.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/back/victreebelb.pic"
TentacoolPicFront::   INCBIN "gfx/pokemon/front/tentacool.pic"
TentacoolPicBack::    INCBIN "gfx/pokemon/back/tentacoolb.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/front/tentacruel.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/back/tentacruelb.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/front/geodude.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/back/geodudeb.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/front/graveler.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/back/gravelerb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/front/golem.pic"
GolemPicBack::        INCBIN "gfx/pokemon/back/golemb.pic"


SECTION "Pics 4", ROMX

PonytaPicFront::      INCBIN "gfx/pokemon/front/ponyta.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/back/ponytab.pic"
RapidashPicFront::    INCBIN "gfx/pokemon/front/rapidash.pic"
RapidashPicBack::     INCBIN "gfx/pokemon/back/rapidashb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/front/slowpoke.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/back/slowpokeb.pic"
SlowbroPicFront::     INCBIN "gfx/pokemon/front/slowbro.pic"
SlowbroPicBack::      INCBIN "gfx/pokemon/back/slowbrob.pic"
MSlowbroPicFront::    INCBIN "gfx/pokemon/front/mslowbro.pic"
MSlowbroPicBack::     INCBIN "gfx/pokemon/back/mslowbrob.pic"
SlowkingPicFront::    INCBIN "gfx/pokemon/front/slowking.pic"
SlowkingPicBack::     INCBIN "gfx/pokemon/back/slowkingb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/front/magnemite.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/back/magnemiteb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/front/magneton.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/back/magnetonb.pic"
MagnezonePicFront::   INCBIN "gfx/pokemon/front/magnezone.pic"
MagnezonePicBack::    INCBIN "gfx/pokemon/back/magnezoneb.pic"
FarfetchdPicFront::   INCBIN "gfx/pokemon/front/farfetchd.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/back/farfetchdb.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/front/doduo.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/back/doduob.pic"
DodrioPicFront::      INCBIN "gfx/pokemon/front/dodrio.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/back/dodriob.pic"
SeelPicFront::        INCBIN "gfx/pokemon/front/seel.pic"
SeelPicBack::         INCBIN "gfx/pokemon/back/seelb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/front/dewgong.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/back/dewgongb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/front/grimer.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/back/grimerb.pic"
MukPicFront::         INCBIN "gfx/pokemon/front/muk.pic"
MukPicBack::          INCBIN "gfx/pokemon/back/mukb.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/front/shellder.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/back/shellderb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/front/cloyster.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/back/cloysterb.pic"
GastlyPicFront::      INCBIN "gfx/pokemon/front/gastly.pic"
GastlyPicBack::       INCBIN "gfx/pokemon/back/gastlyb.pic"
HaunterPicFront::     INCBIN "gfx/pokemon/front/haunter.pic"
HaunterPicBack::      INCBIN "gfx/pokemon/back/haunterb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/front/gengar.pic"
GengarPicBack::       INCBIN "gfx/pokemon/back/gengarb.pic"
MGengarPicFront::     INCBIN "gfx/pokemon/front/mgengar.pic"
MGengarPicBack::      INCBIN "gfx/pokemon/back/mgengarb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/front/onix.pic"
OnixPicBack::         INCBIN "gfx/pokemon/back/onixb.pic"
SteelixPicFront::     INCBIN "gfx/pokemon/front/steelix.pic"
SteelixPicBack::      INCBIN "gfx/pokemon/back/steelixb.pic"
MSteelixPicFront::    INCBIN "gfx/pokemon/front/msteelix.pic"
MSteelixPicBack::     INCBIN "gfx/pokemon/back/msteelixb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/front/drowzee.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/back/drowzeeb.pic"
HypnoPicFront::       INCBIN "gfx/pokemon/front/hypno.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/back/hypnob.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/front/krabby.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/back/krabbyb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/front/kingler.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/back/kinglerb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/front/voltorb.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/back/voltorbb.pic"


SECTION "Pics 5", ROMX

ElectrodePicFront::   INCBIN "gfx/pokemon/front/electrode.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/back/electrodeb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/front/exeggcute.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/back/exeggcuteb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/front/exeggutor.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/back/exeggutorb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/front/cubone.pic"
CubonePicBack::       INCBIN "gfx/pokemon/back/cuboneb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/front/marowak.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/back/marowakb.pic"
TyroguePicFront::     INCBIN "gfx/pokemon/front/tyrogue.pic"
TyroguePicBack::      INCBIN "gfx/pokemon/back/tyrogueb.pic"
HitmonleePicFront::   INCBIN "gfx/pokemon/front/hitmonlee.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/back/hitmonleeb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/front/hitmonchan.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/back/hitmonchanb.pic"
HitmontopPicFront::   INCBIN "gfx/pokemon/front/hitmontop.pic"
HitmontopPicBack::    INCBIN "gfx/pokemon/back/hitmontopb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/front/lickitung.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/back/lickitungb.pic"
LickilickyPicFront::  INCBIN "gfx/pokemon/front/lickilicky.pic"
LickilickyPicBack::   INCBIN "gfx/pokemon/back/lickilickyb.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/front/koffing.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/back/koffingb.pic"
WeezingPicFront::     INCBIN "gfx/pokemon/front/weezing.pic"
WeezingPicBack::      INCBIN "gfx/pokemon/back/weezingb.pic"
RhyhornPicFront::     INCBIN "gfx/pokemon/front/rhyhorn.pic"
RhyhornPicBack::      INCBIN "gfx/pokemon/back/rhyhornb.pic"
RhydonPicFront::      INCBIN "gfx/pokemon/front/rhydon.pic"
RhydonPicBack::       INCBIN "gfx/pokemon/back/rhydonb.pic"
RhyperiorPicFront::   INCBIN "gfx/pokemon/front/rhyperior.pic"
RhyperiorPicBack::    INCBIN "gfx/pokemon/back/rhyperiorb.pic"
HappinyPicFront::     INCBIN "gfx/pokemon/front/happiny.pic"
HappinyPicBack::      INCBIN "gfx/pokemon/back/happinyb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/front/chansey.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/back/chanseyb.pic"
BlisseyPicFront::     INCBIN "gfx/pokemon/front/blissey.pic"
BlisseyPicBack::      INCBIN "gfx/pokemon/back/blisseyb.pic"
TangelaPicFront::     INCBIN "gfx/pokemon/front/tangela.pic"
TangelaPicBack::      INCBIN "gfx/pokemon/back/tangelab.pic"
TangrowthPicFront::   INCBIN "gfx/pokemon/front/tangrowth.pic"
TangrowthPicBack::    INCBIN "gfx/pokemon/back/tangrowthb.pic"


SECTION "Pics 6", ROMX

YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
;JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic" ; commented out
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
;ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
;CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic" ; commented out
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"


SECTION "Pics 6b", ROMX ; new

; new trainer classes, "init_battle" has been modified to handle this bank too
DiverPic::         INCBIN "gfx/trainers/diver.pic"
OragePic::         INCBIN "gfx/trainers/orage.pic"

; TBE
ProtonPic::
PetrelPic::
ArianaPic::
ArcherPic::
CarrPic::
OrmPic::
SirdPic::
IchinoPic::
NiuePic::
SantrePic::
YottroPic::
GonquePic::
RokuseiPic::
NanettePic::
SuujeroPic::
PinkPic::          INCBIN "gfx/trainers/pink.pic"
PigeonPic::        INCBIN "gfx/trainers/pigeon.pic"
JessieJamesPic::   INCBIN "gfx/trainers/jessiejames.pic"
BFTrainerPic::
TravelerPic::      INCBIN "gfx/trainers/traveler.pic"
RocketAdminMPic::  INCBIN "gfx/trainers/rocketadminm.pic"
RocketAdminFPic::  INCBIN "gfx/trainers/rocketadminf.pic"
Traveler2Pic::     INCBIN "gfx/trainers/traveler2.pic"
MissingNoTPic::    INCBIN "gfx/trainers/missingno.pic"

SECTION "Pics 7", ROMX

RedPicBack::       INCBIN "gfx/player/redb.pic"
GreenPicBack::     INCBIN "gfx/player/greenb.pic"
YellowPicBack::    INCBIN "gfx/player/yellowb.pic"
OldManPicBack::    INCBIN "gfx/battle/oldmanb.pic"
ProfOakPicBack::   INCBIN "gfx/battle/prof.oakb.pic"


SECTION "Pics 8", ROMX

KangaskhanPicFront::  INCBIN "gfx/pokemon/front/kangaskhan.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/back/kangaskhanb.pic"
MKangaskanPicFront::  INCBIN "gfx/pokemon/front/mkangaskan.pic"
MKangaskanPicBack::   INCBIN "gfx/pokemon/back/mkangaskanb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/front/horsea.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/back/horseab.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/front/seadra.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/back/seadrab.pic"
KingdraPicFront::     INCBIN "gfx/pokemon/front/kingdra.pic"
KingdraPicBack::      INCBIN "gfx/pokemon/back/kingdrab.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/front/goldeen.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/back/goldeenb.pic"
SeakingPicFront::     INCBIN "gfx/pokemon/front/seaking.pic"
SeakingPicBack::      INCBIN "gfx/pokemon/back/seakingb.pic"
StaryuPicFront::      INCBIN "gfx/pokemon/front/staryu.pic"
StaryuPicBack::       INCBIN "gfx/pokemon/back/staryub.pic"
StarmiePicFront::     INCBIN "gfx/pokemon/front/starmie.pic"
StarmiePicBack::      INCBIN "gfx/pokemon/back/starmieb.pic"
MimeJrPicFront::      INCBIN "gfx/pokemon/front/mimejr.pic"
MimeJrPicBack::       INCBIN "gfx/pokemon/back/mimejrb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/front/mrmime.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/back/mrmimeb.pic"
ScytherPicFront::     INCBIN "gfx/pokemon/front/scyther.pic"
ScytherPicBack::      INCBIN "gfx/pokemon/back/scytherb.pic"
ScizorPicFront::      INCBIN "gfx/pokemon/front/scizor.pic"
ScizorPicBack::       INCBIN "gfx/pokemon/back/scizorb.pic"
MScizorPicFront::     INCBIN "gfx/pokemon/front/mscizor.pic"
MScizorPicBack::      INCBIN "gfx/pokemon/back/mscizorb.pic"
KleavorPicFront::     INCBIN "gfx/pokemon/front/kleavor.pic"
KleavorPicBack::      INCBIN "gfx/pokemon/back/kleavorb.pic"
SmoochumPicFront::    INCBIN "gfx/pokemon/front/smoochum.pic"
SmoochumPicBack::     INCBIN "gfx/pokemon/back/smoochumb.pic"
JynxPicFront::        INCBIN "gfx/pokemon/front/jynx.pic"
JynxPicBack::         INCBIN "gfx/pokemon/back/jynxb.pic"
ElekidPicFront::      INCBIN "gfx/pokemon/front/elekid.pic"
ElekidPicBack::       INCBIN "gfx/pokemon/back/elekidb.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/front/electabuzz.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/back/electabuzzb.pic"
ElectivirePicFront::  INCBIN "gfx/pokemon/front/electivire.pic"
ElectivirePicBack::   INCBIN "gfx/pokemon/back/electivireb.pic"
MagbyPicFront::       INCBIN "gfx/pokemon/front/magby.pic"
MagbyPicBack::        INCBIN "gfx/pokemon/back/magbyb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/front/magmar.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/back/magmarb.pic"
MagmortarPicFront::   INCBIN "gfx/pokemon/front/magmortar.pic"
MagmortarPicBack::    INCBIN "gfx/pokemon/back/magmortarb.pic"
PinsirPicFront::      INCBIN "gfx/pokemon/front/pinsir.pic"
PinsirPicBack::       INCBIN "gfx/pokemon/back/pinsirb.pic"
MPinsirPicFront::     INCBIN "gfx/pokemon/front/mpinsir.pic"
MPinsirPicBack::      INCBIN "gfx/pokemon/back/mpinsirb.pic"


SECTION "Pics 9", ROMX

TaurosPicFront::      INCBIN "gfx/pokemon/front/tauros.pic"
TaurosPicBack::       INCBIN "gfx/pokemon/back/taurosb.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/front/magikarp.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/back/magikarpb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/front/gyarados.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/back/gyaradosb.pic"
MGyaradosPicFront::   INCBIN "gfx/pokemon/front/mgyarados.pic"
MGyaradosPicBack::    INCBIN "gfx/pokemon/back/mgyaradosb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/front/lapras.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/back/laprasb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/front/ditto.pic"
DittoPicBack::        INCBIN "gfx/pokemon/back/dittob.pic"
EeveePicFront::       INCBIN "gfx/pokemon/front/eevee.pic"
EeveePicBack::        INCBIN "gfx/pokemon/back/eeveeb.pic"
VaporeonPicFront::    INCBIN "gfx/pokemon/front/vaporeon.pic"
VaporeonPicBack::     INCBIN "gfx/pokemon/back/vaporeonb.pic"
JolteonPicFront::     INCBIN "gfx/pokemon/front/jolteon.pic"
JolteonPicBack::      INCBIN "gfx/pokemon/back/jolteonb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/front/flareon.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/back/flareonb.pic"
EspeonPicFront::      INCBIN "gfx/pokemon/front/espeon.pic"
EspeonPicBack::       INCBIN "gfx/pokemon/back/espeonb.pic"
UmbreonPicFront::     INCBIN "gfx/pokemon/front/umbreon.pic"
UmbreonPicBack::      INCBIN "gfx/pokemon/back/umbreonb.pic"
LeafeonPicFront::     INCBIN "gfx/pokemon/front/leafeon.pic"
LeafeonPicBack::      INCBIN "gfx/pokemon/back/leafeonb.pic"
GlaceonPicFront::     INCBIN "gfx/pokemon/front/glaceon.pic"
GlaceonPicBack::      INCBIN "gfx/pokemon/back/glaceonb.pic"
SylveonPicFront::     INCBIN "gfx/pokemon/front/sylveon.pic"
SylveonPicBack::      INCBIN "gfx/pokemon/back/sylveonb.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/front/porygon.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/back/porygonb.pic"
Porygon2PicFront::    INCBIN "gfx/pokemon/front/porygon2.pic"
Porygon2PicBack::     INCBIN "gfx/pokemon/back/porygon2b.pic"
PorygonZPicFront::    INCBIN "gfx/pokemon/front/porygonz.pic"
PorygonZPicBack::     INCBIN "gfx/pokemon/back/porygonzb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/front/omanyte.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/back/omanyteb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/front/omastar.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/back/omastarb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/front/kabuto.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/back/kabutob.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/front/kabutops.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/back/kabutopsb.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/front/aerodactyl.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/back/aerodactylb.pic"
MArodactylPicFront::  INCBIN "gfx/pokemon/front/marodactyl.pic"
MArodactylPicBack::   INCBIN "gfx/pokemon/back/marodactylb.pic"


SECTION "Pics 10", ROMX

MunchlaxPicFront::    INCBIN "gfx/pokemon/front/munchlax.pic"
MunchlaxPicBack::     INCBIN "gfx/pokemon/back/munchlaxb.pic"
SnorlaxPicFront::     INCBIN "gfx/pokemon/front/snorlax.pic"
SnorlaxPicBack::      INCBIN "gfx/pokemon/back/snorlaxb.pic"
ArticunoPicFront::    INCBIN "gfx/pokemon/front/articuno.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/back/articunob.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/front/zapdos.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/back/zapdosb.pic"
MoltresPicFront::     INCBIN "gfx/pokemon/front/moltres.pic"
MoltresPicBack::      INCBIN "gfx/pokemon/back/moltresb.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/front/dratini.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/back/dratinib.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/front/dragonair.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/back/dragonairb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/front/dragonite.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/back/dragoniteb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/front/mewtwo.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/back/mewtwob.pic"
MMewtwoXPicFront::    INCBIN "gfx/pokemon/front/mmewtwox.pic"
MMewtwoXPicBack::     INCBIN "gfx/pokemon/back/mmewtwoxb.pic"
MMewtwoYPicFront::    INCBIN "gfx/pokemon/front/mmewtwoy.pic"
MMewtwoYPicBack::     INCBIN "gfx/pokemon/back/mmewtwoyb.pic"
MewPicFront::         INCBIN "gfx/pokemon/front/mew.pic"
MewPicBack::          INCBIN "gfx/pokemon/back/mewb.pic"
VenustoisePicFront::  INCBIN "gfx/pokemon/front/venustoise.pic"
VenustoisePicBack::   INCBIN "gfx/pokemon/back/venustoiseb.pic"

ZygardeCPicFront::  INCBIN "gfx/pokemon/front/zygardec.pic"
ZygardeCPicBack::   INCBIN "gfx/pokemon/back/zygardecb.pic"
UNecrozmaPicFront::  INCBIN "gfx/pokemon/front/unecrozma.pic"
UNecrozmaPicBack::   INCBIN "gfx/pokemon/back/unecrozmab.pic"
MRayquazaPicFront::  INCBIN "gfx/pokemon/front/mrayquaza.pic"
MRayquazaPicBack::   INCBIN "gfx/pokemon/back/mrayquazab.pic"
EEternatusPicFront::  INCBIN "gfx/pokemon/front/eeternatus.pic"
EEternatusPicBack::   INCBIN "gfx/pokemon/back/eeternatusb.pic"
ArceusPicFront::  INCBIN "gfx/pokemon/front/arceus.pic"
ArceusPicBack::   INCBIN "gfx/pokemon/back/arceusb.pic"
MissingNoPicFront::  INCBIN "gfx/pokemon/front/missingno.pic"
MissingNoPicBack::   INCBIN "gfx/pokemon/back/missingnob.pic"
BluesDadPicFront::  INCBIN "gfx/pokemon/front/bluesdad.pic"
BluesMomPicFront::  INCBIN "gfx/pokemon/front/bluesmom.pic"
DadPicFront::  INCBIN "gfx/pokemon/front/dad.pic"
BluesDadPicBack::
BluesMomPicBack::
DadPicBack::   INCBIN "gfx/pokemon/back/dadb.pic" ; just one, they are all proxies

FossilKabutopsPic::   INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic::  INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::             INCBIN "gfx/battle/ghost.pic"

; map pieces, new
MysteryMap1Pic::   INCBIN "gfx/pokemon/front/mysterymap1.pic"
MysteryMap2Pic::   INCBIN "gfx/pokemon/front/mysterymap2.pic"
MysteryMap3Pic::   INCBIN "gfx/pokemon/front/mysterymap3.pic"
MysteryMap4Pic::   INCBIN "gfx/pokemon/front/mysterymap4.pic"
MysteryMap12Pic::   INCBIN "gfx/pokemon/front/mysterymap12.pic"
MysteryMap13Pic::   INCBIN "gfx/pokemon/front/mysterymap13.pic"
MysteryMap14Pic::   INCBIN "gfx/pokemon/front/mysterymap14.pic"
MysteryMap23Pic::   INCBIN "gfx/pokemon/front/mysterymap23.pic"
MysteryMap24Pic::   INCBIN "gfx/pokemon/front/mysterymap24.pic"
MysteryMap34Pic::   INCBIN "gfx/pokemon/front/mysterymap34.pic"
MysteryMap123Pic::   INCBIN "gfx/pokemon/front/mysterymap123.pic"
MysteryMap124Pic::   INCBIN "gfx/pokemon/front/mysterymap124.pic"
MysteryMap134Pic::   INCBIN "gfx/pokemon/front/mysterymap134.pic"
MysteryMap234Pic::   INCBIN "gfx/pokemon/front/mysterymap234.pic"
MysteryMap1234Pic::   INCBIN "gfx/pokemon/front/mysterymap1234.pic"
