RedPicFront:: INCBIN "gfx/player/red.pic"
GreenPicFront:: INCBIN "gfx/player/green.pic"
YellowPicFront:: INCBIN "gfx/player/yellow.pic"
ShrinkPic1::  INCBIN "gfx/player/shrink1.pic"
ShrinkPic2::  INCBIN "gfx/player/shrink2.pic"
RedRocketPicFront:: INCBIN "gfx/player/red_rocket.pic"
GreenRocketPicFront:: INCBIN "gfx/player/green_rocket.pic"
YellowRocketPicFront:: INCBIN "gfx/player/yellow_rocket.pic"
