; from Vortiene:
; in Evolution_PartyMonLoop
; copydata is a function that copies hl to de for bc amount of bytes
; in this case, it's copying data from base stats data to wMonHeader
; for the current pokemon
; since wMonHeader will have everything you need for this whole Evolution code after doing this copy, and the wram value will stay the same regardless of the bank you're in
; all you need to do is run this code specifically in the same bank as base stats then go back to the evolution bank
; which can all be achieved by just callfar'ing a function that does the above code in the base stats bank then returns

BaseStatsCopying::
	ld a, [wd11e]
	dec a
	ld hl, BaseStats
	ld bc, BASE_DATA_SIZE
	call AddNTimes
	ld de, wMonHeader
	call CopyData ; function that copies hl to de for bc amount of bytes = so BaseStats is copied into wMonHeader for BASE_DATA_SIZE amount of bytes

; new, for TCG mode
	ld a, [wPersonalizationTCGMode]
	and a
	jr z, .checkVanillaDelta
	ld hl, ListOfMonsAndTypesToChange_TCG
	jr .listOfTypesGotten

.checkVanillaDelta
; new, for delta species, TBE for delta AND TCG
	CheckAndResetEvent EVENT_LOAD_DELTA_SPECIES_TYPES
	jr z, .checkAlteredTypes
	ld hl, ListOfMonsAndTypesToChange_Delta
	jr .listOfTypesGotten

.checkAlteredTypes
; new, to personalize types
	ld a, [wPersonalizationTypes] ; 0=CLASSIC, 1=NEW
	and a
	ret z ; if types are the hard-coded ones, we're good
; otherwise, overwrite them
	ld hl, ListOfMonsAndTypesToChange_Altered
.listOfTypesGotten
	ld a, [wd11e]
	ld b, a ; b holds the current mon species
.loopTypesToChange
	ld a, [hli] ; a points to the mon species entry, and hl points to the first type
	cp -1 ; terminator
	ret z
; we didn't hit the terminator
	cp b ; is the current pokemon we're looking at the same as the table entry?
	jr nz, .increaseHLby2 ; if not, go to the next entry
; it's a match!
	ld a, [hli] ; a contains the first new type, hl points to the second new type
	ld [wMonHType1], a
	ld a, [hl]
	ld [wMonHType2], a
	ret
.increaseHLby2
	inc hl ; hl points to the second type
	inc hl ; hl points to the next mon species
	jr .loopTypesToChange

ListOfMonsAndTypesToChange_Altered:
	db VENUSAUR, GRASS, GROUND
	db MVENUSAUR, GRASS, GROUND
	db CHARIZARD, FIRE, DRAGON
	db MCHARZARDY, FIRE, DRAGON
	db BLASTOISE, WATER, STEEL
	db MBLASTOISE, WATER, STEEL
	db BUTTERFREE, BUG, PSYCHIC_TYPE
	db PIDGEY, FLYING, FLYING
	db PIDGEOTTO, FLYING, FLYING
	db PIDGEOT, FLYING, FLYING
	db MPIDGEOT, FLYING, FLYING
	db RATTATA, NORMAL, GROUND
	db RATICATE, NORMAL, GROUND
	db SPEAROW, FLYING, FIGHTING
	db FEAROW, FLYING, FIGHTING
	db ARBOK, POISON, DARK
	db PICHU, ELECTRIC, GROUND ; V2
	db PIKACHU, ELECTRIC, GROUND ; V2
	db RAICHU, ELECTRIC, GROUND ; V2
	db MRAICHUX, ELECTRIC, FLYING ; V2
	db MRAICHUY, ELECTRIC, FAIRY ; V2
	db NIDOQUEEN, POISON, FAIRY
	db NIDOKING, POISON, FIGHTING
	db VULPIX, FIRE, GHOST
	db NINETALES, FIRE, GHOST
	db ZUBAT, DARK, FLYING ; V2
	db GOLBAT, DARK, FLYING ; V2
	db CROBAT, DARK, FLYING ; V2
	db BELLOSSOM, GRASS, FIRE
	db PARAS, BUG, GHOST
	db PARASECT, BUG, GHOST
	db VENOMOTH, POISON, PSYCHIC_TYPE
	db PSYDUCK, WATER, PSYCHIC_TYPE
	db GOLDUCK, WATER, PSYCHIC_TYPE
	db PRIMEAPE, FIGHTING, DARK
	db ARCANINE, FIRE, DRAGON
	db GEODUDE, ROCK, ROCK
	db GRAVELER, ROCK, ROCK
	db GOLEM, ROCK, ROCK
	db PONYTA, FIRE, GROUND
	db RAPIDASH, FIRE, GROUND
	db DODUO, FLYING, GROUND
	db DODRIO, FLYING, GROUND
	db DEWGONG, ICE, FAIRY
	db GRIMER, POISON, GROUND
	db MUK, POISON, GROUND
	db SHELLDER, WATER, ROCK
	db CLOYSTER, ICE, ROCK
	db GASTLY, GHOST, DARK
	db HAUNTER, GHOST, DARK
	db GENGAR, GHOST, DARK
	db MGENGAR, GHOST, DARK
	db DROWZEE, PSYCHIC_TYPE, DARK
	db HYPNO, PSYCHIC_TYPE, DARK
	db KRABBY, WATER, BUG
	db KINGLER, WATER, BUG
	db VOLTORB, ELECTRIC, FIRE
	db ELECTRODE, ELECTRIC, FIRE
	db CUBONE, GROUND, GHOST
	db MAROWAK, GROUND, GHOST
	db HITMONLEE, FIGHTING, GROUND
	db HITMONCHAN, FIGHTING, NORMAL
	db HITMONTOP, FIGHTING, FLYING
	db KOFFING, POISON, FIRE
	db WEEZING, POISON, FIRE
	db RHYDON, ROCK, FIGHTING
	db RHYPERIOR, ROCK, FIGHTING
	db HAPPINY, FAIRY, FAIRY
	db CHANSEY, FAIRY, FAIRY
	db BLISSEY, FAIRY, FAIRY
	db TANGELA, GRASS, DARK
	db TANGROWTH, GRASS, DARK
	db SEADRA, WATER, POISON
	db KINGDRA, DRAGON, POISON
	db GOLDEEN, WATER, NORMAL
	db SEAKING, WATER, NORMAL
	db STARYU, WATER, FAIRY
	db STARMIE, WATER, FAIRY
	db MSTARMIE, WATER, FAIRY ; V2
	db ELEKID, ELECTRIC, FIGHTING
	db ELECTABUZZ, ELECTRIC, FIGHTING
	db ELECTIVIRE, ELECTRIC, FIGHTING
	db MAGBY, FIRE, DARK
	db MAGMAR, FIRE, DARK
	db MAGMORTAR, FIRE, DARK
	db TAUROS, NORMAL, GROUND
	db GYARADOS, WATER, DRAGON
	db PORYGON, ELECTRIC, GHOST
	db PORYGON2, ELECTRIC, GHOST
	db PORYGONZ, ELECTRIC, GHOST
	db KABUTO, ROCK, BUG
	db KABUTOPS, ROCK, BUG
	db AERODACTYL, ROCK, DRAGON
	db MARODACTYL, ROCK, DRAGON
	db DRATINI, DRAGON, FAIRY
	db DRAGONAIR, DRAGON, FAIRY
	db DRAGONITE, DRAGON, FAIRY
	db MDRAGONITE, DRAGON, FAIRY ; V2
	db -1

UpdatePartyMonTypesAfterPersonalization:
; do nothing if we don't have a party
	ld a, [wPartyCount]
	and a
	ret z
; do something if we have a party
	ld a, [wPersonalizationTypes] ; 0=NO, 1=YES
	and a
	jr z, .vanillaTypes
; new types
	ld a, [wPartyCount]
	ld c, a ; c is the counter
.loopUpdateNew
	ld a, [wPartyCount]
	sub c ; a-c
	push bc

; get the header of the mon of this round of the party loop
	ld hl, wPartyMon1
	ld bc, wPartyMon2 - wPartyMon1
	call AddNTimes
	push hl ; hl points to the header of the "a-c"th mon in the party
	ld bc, wPartyMon1Species - wPartyMon1
	add hl, bc ; hl points to the species of the "a-c"th mon in the party
; check if the species needs treatement
	ld a, [hl]
	ld b, a ; b holds the current mon species
	ld de, ListOfMonsAndTypesToChange_Altered
.loopTypesToChange
	ld a, [de] ; a points to the mon species entry, and de points to the first type
	inc de
	cp -1 ; terminator
	jr z, .matchNotFound
; we didn't hit the terminator
	cp b ; is the current pokemon we're looking at the same as the table entry?
	jr nz, .increaseDEby2 ; if not, go to the next entry
; it's a match!
	jr .matchFound
.increaseDEby2
	inc de ; de points to the second type
	inc de ; de points to the next mon species
	jr .loopTypesToChange
.matchNotFound
	pop hl
	jr .completeThisRoundOfPartLoop

.matchFound
	pop hl ; hl points again to the header of the "a-c"th mon in the party
	ld bc, wPartyMon1Type - wPartyMon1 ; $5
	add hl, bc
; now hl points to the 1st type of the "a-c"th mon in the party
	ld a, [de] ; a contains the first new type, de points to the second new type
	inc de
	ld [hl], a
	inc hl
	ld a, [de]
	ld [hl], a

.completeThisRoundOfPartLoop
	pop bc
	dec c
	jr nz, .loopUpdateNew
	ret

.vanillaTypes
; here we need to restore the types to the vanilla one, so can take it simpler,
; and just re-write the types of EVERY party's mon with the header's ones
; insignificantly slower when playing, so much cleaner and simpler to read here

	ld a, [wPartyCount]
	ld c, a ; c is the counter
.loopUpdateVanilla
	ld a, [wPartyCount]
	sub c ; a-c
	push bc

; get the header of the mon of this round of the party loop
	ld hl, wPartyMon1
	ld bc, wPartyMon2 - wPartyMon1
	call AddNTimes ; hl points to the header of the "a-c"th mon in the party
	ld bc, wPartyMon1Species - wPartyMon1
	add hl, bc ; hl points to the species of the "a-c"th mon in the party
	push hl

	ld a, [hl]
	dec a
	ld hl, BaseStats
	ld bc, BASE_DATA_SIZE
	call AddNTimes
	ld de, wMonHeader
	call CopyData

	pop hl
	ld bc, wPartyMon1Type - wPartyMon1 ; $5
	add hl, bc ; now hl points to the 1st type of the "a-c"th mon in the party

	ld a, [wMonHType1]
	ld [hl], a
	inc hl
	ld a, [wMonHType2]
	ld [hl], a

	pop bc
	dec c
	jr nz, .loopUpdateVanilla
	ret

; input: mon species in d
; outpit: types in d and e
ExtractMonsTypesForMovingIntoParty::
	ld a, [wPersonalizationTypes] ; 0=NO, 1=YES
	and a
	jr z, .vanillaTypes

; new types
	push de
	ld a, d
	ld b, a ; b holds the current mon species
	ld hl, ListOfMonsAndTypesToChange_Altered
.loopTypesToChange
	ld a, [hl] ; a points to the mon species entry, and hl points to the first type
	inc hl
	cp -1 ; terminator
	jr z, .matchNotFound
; we didn't hit the terminator
	cp b ; is the current pokemon we're looking at the same as the table entry?
	jr nz, .increasehlby2 ; if not, go to the next entry
; it's a match!
	jr .matchFound
.increasehlby2
	inc hl ; hl points to the second type
	inc hl ; hl points to the next mon species
	jr .loopTypesToChange
.matchFound
	pop de
	ld a, [hl]
	ld d, a
	ld a, [hl]
	ld e, a
	ret
.matchNotFound
	pop de
; fallthrough

.vanillaTypes
	ld a, d ; a has the mon's species
	dec a
	ld hl, BaseStats
	ld bc, BASE_DATA_SIZE
	call AddNTimes
	ld de, wMonHeader
	call CopyData

	ld a, [wMonHType1]
	ld d, a
	ld a, [wMonHType2]
	ld e, a
	ret

; mon ID in d
; c flag if match found
CheckIfMonHasDeltaSpecies::
	ld hl, ListOfMonsAndTypesToChange_Delta
.loop
	ld a, [hli] ; hl points now to the first type
	cp -1 ; terminator
	jr z, .unsetCFlag
	cp d
	jr z, .setCFlag ; match found
	inc hl
	inc hl
	jr .loop
.setCFlag
	scf
	ret
.unsetCFlag
	xor a
	ret

ListOfMonsAndTypesToChange_Delta:
; 1
	db WEEDLE, GRASS, GRASS
	db KAKUNA, GRASS, GRASS
	db BEEDRILL, GRASS, STEEL
	db MBEEDRILL, GRASS, STEEL
	db SANDSHREW, ROCK, ROCK
	db SANDSLASH, ROCK, STEEL
	db PICHU, STEEL, STEEL
	db PIKACHU, STEEL, STEEL
	db RAICHU, STEEL, STEEL
	db MRAICHUX, STEEL, STEEL
	db MRAICHUY, STEEL, STEEL
	db PIDGEY, ELECTRIC, ELECTRIC
	db PIDGEOTTO, ELECTRIC, ELECTRIC
	db PIDGEOT, ELECTRIC, STEEL
	db MPIDGEOT, ELECTRIC, STEEL
	db MANKEY, FIRE, FIRE
	db PRIMEAPE, FIRE, FIRE
	db ANNIHILAPE, FIRE, FIRE
	db SPEAROW, ELECTRIC, ELECTRIC
	db FEAROW, ELECTRIC, ELECTRIC
	db ZUBAT, BUG, STEEL
	db GOLBAT, BUG, STEEL
	db CROBAT, BUG, STEEL
	db HORSEA, FIRE, ROCK
	db SEADRA, FIRE, ROCK
	db KINGDRA, FIRE, ROCK
	db KRABBY, FIRE, FIRE
	db KINGLER, FIRE, STEEL
; 2
	db EEVEE, STEEL, STEEL
	db ESPEON, PSYCHIC_TYPE, STEEL
	db FLAREON, FIRE, STEEL
	db JOLTEON, ELECTRIC, STEEL
	db UMBREON, DARK, STEEL
	db VAPOREON, WATER, STEEL
	db ODDISH, FAIRY, FAIRY
	db GLOOM, FAIRY, FAIRY
	db VILEPLUME, FAIRY, STEEL
	db BELLOSSOM, WATER, WATER
	db MEOWTH, DARK, STEEL
	db PERSIAN, DARK, STEEL
	db EKANS, FIRE, FIRE
	db ARBOK, FIRE, FIRE
	db VULPIX, PSYCHIC_TYPE, FAIRY
	db NINETALES, PSYCHIC_TYPE, FAIRY
	db NIDORAN_F, STEEL, STEEL
	db NIDORINA, STEEL, STEEL
	db NIDOQUEEN, STEEL, STEEL
	db NIDORAN_M, DARK, DARK
	db NIDORINO, DARK, DARK
	db NIDOKING, DARK, DARK
	db PSYDUCK, ELECTRIC, ELECTRIC
	db GOLDUCK, ELECTRIC, ELECTRIC
	db SHELLDER, FIGHTING, ROCK
	db CLOYSTER, FIGHTING, ROCK
	db SEEL, NORMAL, DRAGON
	db DEWGONG, NORMAL, DRAGON
; 3
	db SMOOCHUM, FIRE, FIRE
	db JYNX, FIRE, FIRE
	db LICKITUNG, PSYCHIC_TYPE, GHOST
	db LICKILICKY, PSYCHIC_TYPE, GHOST
	db ELEKID, GROUND, GROUND
	db ELECTABUZZ, GROUND, GROUND
	db ELECTIVIRE, GROUND, GROUND
	db EXEGGCUTE, ROCK, ROCK
	db EXEGGUTOR, ROCK, ROCK
	db CHARMANDER, ELECTRIC, ELECTRIC
	db CHARMELEON, ELECTRIC, ELECTRIC
	db CHARIZARD, ELECTRIC, DARK
	db MCHARZARDX, ELECTRIC, DARK
	db MCHARZARDY, ELECTRIC, DARK
	db BULBASAUR, ICE, GHOST
	db IVYSAUR, ICE, GHOST
	db VENUSAUR, ICE, GHOST
	db MVENUSAUR, ICE, GHOST
	db SQUIRTLE, ROCK, ROCK
	db WARTORTLE, ROCK, ROCK
	db BLASTOISE, ROCK, STEEL
	db MBLASTOISE, ROCK, STEEL
	db MAGIKARP, STEEL, STEEL
	db GYARADOS, ELECTRIC, FIRE
	db MGYARADOS, ELECTRIC, FIRE
	db STARYU, ICE, ICE
	db STARMIE, ICE, STEEL
	db MSTARMIE, ICE, STEEL
; 4
	db PINSIR, GROUND, FIGHTING
	db MPINSIR, GROUND, FIGHTING
	db MUNCHLAX, BUG, BUG
	db SNORLAX, BUG, BUG
	db AERODACTYL, FIRE, FIRE
	db MARODACTYL, FIRE, FIRE
	db CUBONE, FIGHTING, FIGHTING
	db MAROWAK, FIGHTING, STEEL
	db DRATINI, ELECTRIC, GRASS
	db DRAGONAIR, ELECTRIC, GRASS
	db DRAGONITE, ELECTRIC, GRASS
	db MDRAGONITE, ELECTRIC, GRASS
	db KABUTO, ELECTRIC, ELECTRIC
	db KABUTOPS, ELECTRIC, ELECTRIC
	db OMANYTE, GHOST, FAIRY
	db OMASTAR, GHOST, FAIRY
; 5
	db ARM_MEWTWO, FIRE, ELECTRIC
	db MEWTWO, FIRE, ELECTRIC
	db MMEWTWOX, FIRE, ELECTRIC
	db MMEWTWOY, FIRE, ELECTRIC
	db MEW, FIRE, WATER
	db VENUSTOISE, ROCK, GHOST
	db -1

ListOfMonsAndTypesToChange_TCG:
	db BULBASAUR, TCG_COLORLESS, TCG_COLORLESS
	db IVYSAUR, TCG_COLORLESS, TCG_COLORLESS
	db VENUSAUR, TCG_COLORLESS, TCG_COLORLESS
	db MVENUSAUR, TCG_COLORLESS, TCG_COLORLESS
	db CHARMANDER, TCG_COLORLESS, TCG_COLORLESS
	db CHARMELEON, TCG_COLORLESS, TCG_COLORLESS
	db CHARIZARD, TCG_COLORLESS, TCG_COLORLESS
	db MCHARZARDX, TCG_COLORLESS, TCG_COLORLESS
	db MCHARZARDY, TCG_COLORLESS, TCG_COLORLESS
	db SQUIRTLE, TCG_COLORLESS, TCG_COLORLESS
	db WARTORTLE, TCG_COLORLESS, TCG_COLORLESS
	db BLASTOISE, TCG_COLORLESS, TCG_COLORLESS
	db MBLASTOISE, TCG_COLORLESS, TCG_COLORLESS
	db CATERPIE, TCG_COLORLESS, TCG_COLORLESS
	db METAPOD, TCG_COLORLESS, TCG_COLORLESS
	db BUTTERFREE, TCG_COLORLESS, TCG_COLORLESS
	db WEEDLE, TCG_COLORLESS, TCG_COLORLESS
	db KAKUNA, TCG_COLORLESS, TCG_COLORLESS
	db BEEDRILL, TCG_COLORLESS, TCG_COLORLESS
	db MBEEDRILL, TCG_COLORLESS, TCG_COLORLESS
	db PIDGEY, TCG_COLORLESS, TCG_COLORLESS
	db PIDGEOTTO, TCG_COLORLESS, TCG_COLORLESS
	db PIDGEOT, TCG_COLORLESS, TCG_COLORLESS
	db MPIDGEOT, TCG_COLORLESS, TCG_COLORLESS
	db RATTATA, TCG_COLORLESS, TCG_COLORLESS
	db RATICATE, TCG_COLORLESS, TCG_COLORLESS
	db SPEAROW, TCG_COLORLESS, TCG_COLORLESS
	db FEAROW, TCG_COLORLESS, TCG_COLORLESS
	db EKANS, TCG_COLORLESS, TCG_COLORLESS
	db ARBOK, TCG_COLORLESS, TCG_COLORLESS
	db PICHU, TCG_COLORLESS, TCG_COLORLESS
	db PIKACHU, TCG_COLORLESS, TCG_COLORLESS
	db RAICHU, TCG_COLORLESS, TCG_COLORLESS
	db MRAICHUX, TCG_COLORLESS, TCG_COLORLESS
	db MRAICHUY, TCG_COLORLESS, TCG_COLORLESS
	db SANDSHREW, TCG_COLORLESS, TCG_COLORLESS
	db SANDSLASH, TCG_COLORLESS, TCG_COLORLESS
	db NIDORAN_F, TCG_COLORLESS, TCG_COLORLESS
	db NIDORINA, TCG_COLORLESS, TCG_COLORLESS
	db NIDOQUEEN, TCG_COLORLESS, TCG_COLORLESS
	db NIDORAN_M, TCG_COLORLESS, TCG_COLORLESS
	db NIDORINO, TCG_COLORLESS, TCG_COLORLESS
	db NIDOKING, TCG_COLORLESS, TCG_COLORLESS
	db CLEFFA, TCG_COLORLESS, TCG_COLORLESS
	db CLEFAIRY, TCG_COLORLESS, TCG_COLORLESS
	db CLEFABLE, TCG_COLORLESS, TCG_COLORLESS
	db MCLEFABLE, TCG_COLORLESS, TCG_COLORLESS
	db VULPIX, TCG_COLORLESS, TCG_COLORLESS
	db NINETALES, TCG_COLORLESS, TCG_COLORLESS
	db IGGLYBUFF, TCG_COLORLESS, TCG_COLORLESS
	db JIGGLYPUFF, TCG_COLORLESS, TCG_COLORLESS
	db WIGGLYTUFF, TCG_COLORLESS, TCG_COLORLESS
	db ZUBAT, TCG_COLORLESS, TCG_COLORLESS
	db GOLBAT, TCG_COLORLESS, TCG_COLORLESS
	db CROBAT, TCG_COLORLESS, TCG_COLORLESS
	db ODDISH, TCG_COLORLESS, TCG_COLORLESS
	db GLOOM, TCG_COLORLESS, TCG_COLORLESS
	db VILEPLUME, TCG_COLORLESS, TCG_COLORLESS
	db BELLOSSOM, TCG_COLORLESS, TCG_COLORLESS
	db PARAS, TCG_COLORLESS, TCG_COLORLESS
	db PARASECT, TCG_COLORLESS, TCG_COLORLESS
	db VENONAT, TCG_COLORLESS, TCG_COLORLESS
	db VENOMOTH, TCG_COLORLESS, TCG_COLORLESS
	db DIGLETT, TCG_COLORLESS, TCG_COLORLESS
	db DUGTRIO, TCG_COLORLESS, TCG_COLORLESS
	db MEOWTH, TCG_COLORLESS, TCG_COLORLESS
	db PERSIAN, TCG_COLORLESS, TCG_COLORLESS
	db PSYDUCK, TCG_COLORLESS, TCG_COLORLESS
	db GOLDUCK, TCG_COLORLESS, TCG_COLORLESS
	db MANKEY, TCG_COLORLESS, TCG_COLORLESS
	db PRIMEAPE, TCG_COLORLESS, TCG_COLORLESS
	db ANNIHILAPE, TCG_COLORLESS, TCG_COLORLESS
	db GROWLITHE, TCG_COLORLESS, TCG_COLORLESS
	db ARCANINE, TCG_COLORLESS, TCG_COLORLESS
	db POLIWAG, TCG_COLORLESS, TCG_COLORLESS
	db POLIWHIRL, TCG_COLORLESS, TCG_COLORLESS
	db POLIWRATH, TCG_COLORLESS, TCG_COLORLESS
	db POLITOED, TCG_COLORLESS, TCG_COLORLESS
	db ABRA, TCG_COLORLESS, TCG_COLORLESS
	db KADABRA, TCG_COLORLESS, TCG_COLORLESS
	db ALAKAZAM, TCG_COLORLESS, TCG_COLORLESS
	db MALAKAZAM, TCG_COLORLESS, TCG_COLORLESS
	db MACHOP, TCG_COLORLESS, TCG_COLORLESS
	db MACHOKE, TCG_COLORLESS, TCG_COLORLESS
	db MACHAMP, TCG_COLORLESS, TCG_COLORLESS
	db BELLSPROUT, TCG_COLORLESS, TCG_COLORLESS
	db WEEPINBELL, TCG_COLORLESS, TCG_COLORLESS
	db VICTREEBEL, TCG_COLORLESS, TCG_COLORLESS
	db MVICTREBEL, TCG_COLORLESS, TCG_COLORLESS
	db TENTACOOL, TCG_COLORLESS, TCG_COLORLESS
	db TENTACRUEL, TCG_COLORLESS, TCG_COLORLESS
	db GEODUDE, TCG_COLORLESS, TCG_COLORLESS
	db GRAVELER, TCG_COLORLESS, TCG_COLORLESS
	db GOLEM, TCG_COLORLESS, TCG_COLORLESS
	db PONYTA, TCG_COLORLESS, TCG_COLORLESS
	db RAPIDASH, TCG_COLORLESS, TCG_COLORLESS
	db SLOWPOKE, TCG_COLORLESS, TCG_COLORLESS
	db SLOWBRO, TCG_COLORLESS, TCG_COLORLESS
	db MSLOWBRO, TCG_COLORLESS, TCG_COLORLESS
	db SLOWKING, TCG_COLORLESS, TCG_COLORLESS
	db MAGNEMITE, TCG_COLORLESS, TCG_COLORLESS
	db MAGNETON, TCG_COLORLESS, TCG_COLORLESS
	db MAGNEZONE, TCG_COLORLESS, TCG_COLORLESS
	db FARFETCHD, TCG_COLORLESS, TCG_COLORLESS
	db DODUO, TCG_COLORLESS, TCG_COLORLESS
	db DODRIO, TCG_COLORLESS, TCG_COLORLESS
	db SEEL, TCG_COLORLESS, TCG_COLORLESS
	db DEWGONG, TCG_COLORLESS, TCG_COLORLESS
	db GRIMER, TCG_COLORLESS, TCG_COLORLESS
	db MUK, TCG_COLORLESS, TCG_COLORLESS
	db SHELLDER, TCG_COLORLESS, TCG_COLORLESS
	db CLOYSTER, TCG_COLORLESS, TCG_COLORLESS
	db GASTLY, TCG_COLORLESS, TCG_COLORLESS
	db HAUNTER, TCG_COLORLESS, TCG_COLORLESS
	db GENGAR, TCG_COLORLESS, TCG_COLORLESS
	db MGENGAR, TCG_COLORLESS, TCG_COLORLESS
	db ONIX, TCG_COLORLESS, TCG_COLORLESS
	db STEELIX, TCG_COLORLESS, TCG_COLORLESS
	db MSTEELIX, TCG_COLORLESS, TCG_COLORLESS
	db DROWZEE, TCG_COLORLESS, TCG_COLORLESS
	db HYPNO, TCG_COLORLESS, TCG_COLORLESS
	db KRABBY, TCG_COLORLESS, TCG_COLORLESS
	db KINGLER, TCG_COLORLESS, TCG_COLORLESS
	db VOLTORB, TCG_COLORLESS, TCG_COLORLESS
	db ELECTRODE, TCG_COLORLESS, TCG_COLORLESS
	db EXEGGCUTE, TCG_COLORLESS, TCG_COLORLESS
	db EXEGGUTOR, TCG_COLORLESS, TCG_COLORLESS
	db CUBONE, TCG_COLORLESS, TCG_COLORLESS
	db MAROWAK, TCG_COLORLESS, TCG_COLORLESS
	db TYROGUE, TCG_COLORLESS, TCG_COLORLESS
	db HITMONLEE, TCG_COLORLESS, TCG_COLORLESS
	db HITMONCHAN, TCG_COLORLESS, TCG_COLORLESS
	db HITMONTOP, TCG_COLORLESS, TCG_COLORLESS
	db LICKITUNG, TCG_COLORLESS, TCG_COLORLESS
	db LICKILICKY, TCG_COLORLESS, TCG_COLORLESS
	db KOFFING, TCG_COLORLESS, TCG_COLORLESS
	db WEEZING, TCG_COLORLESS, TCG_COLORLESS
	db RHYHORN, TCG_COLORLESS, TCG_COLORLESS
	db RHYDON, TCG_COLORLESS, TCG_COLORLESS
	db RHYPERIOR, TCG_COLORLESS, TCG_COLORLESS
	db HAPPINY, TCG_COLORLESS, TCG_COLORLESS
	db CHANSEY, TCG_COLORLESS, TCG_COLORLESS
	db BLISSEY, TCG_COLORLESS, TCG_COLORLESS
	db TANGELA, TCG_COLORLESS, TCG_COLORLESS
	db TANGROWTH, TCG_COLORLESS, TCG_COLORLESS
	db KANGASKHAN, TCG_COLORLESS, TCG_COLORLESS
	db MKANGASKAN, TCG_COLORLESS, TCG_COLORLESS
	db HORSEA, TCG_COLORLESS, TCG_COLORLESS
	db SEADRA, TCG_COLORLESS, TCG_COLORLESS
	db KINGDRA, TCG_COLORLESS, TCG_COLORLESS
	db GOLDEEN, TCG_COLORLESS, TCG_COLORLESS
	db SEAKING, TCG_COLORLESS, TCG_COLORLESS
	db STARYU, TCG_COLORLESS, TCG_COLORLESS
	db STARMIE, TCG_COLORLESS, TCG_COLORLESS
	db MSTARMIE, TCG_COLORLESS, TCG_COLORLESS
	db MIME_JR, TCG_COLORLESS, TCG_COLORLESS
	db MR_MIME, TCG_COLORLESS, TCG_COLORLESS
	db SCYTHER, TCG_COLORLESS, TCG_COLORLESS
	db SCIZOR, TCG_COLORLESS, TCG_COLORLESS
	db MSCIZOR, TCG_COLORLESS, TCG_COLORLESS
	db KLEAVOR, TCG_COLORLESS, TCG_COLORLESS
	db SMOOCHUM, TCG_COLORLESS, TCG_COLORLESS
	db JYNX, TCG_COLORLESS, TCG_COLORLESS
	db ELEKID, TCG_COLORLESS, TCG_COLORLESS
	db ELECTABUZZ, TCG_COLORLESS, TCG_COLORLESS
	db ELECTIVIRE, TCG_COLORLESS, TCG_COLORLESS
	db MAGBY, TCG_COLORLESS, TCG_COLORLESS
	db MAGMAR, TCG_COLORLESS, TCG_COLORLESS
	db MAGMORTAR, TCG_COLORLESS, TCG_COLORLESS
	db PINSIR, TCG_COLORLESS, TCG_COLORLESS
	db MPINSIR, TCG_COLORLESS, TCG_COLORLESS
	db TAUROS, TCG_COLORLESS, TCG_COLORLESS
	db MAGIKARP, TCG_COLORLESS, TCG_COLORLESS
	db GYARADOS, TCG_COLORLESS, TCG_COLORLESS
	db MGYARADOS, TCG_COLORLESS, TCG_COLORLESS
	db LAPRAS, TCG_COLORLESS, TCG_COLORLESS
	db DITTO, TCG_COLORLESS, TCG_COLORLESS
	db EEVEE, TCG_COLORLESS, TCG_COLORLESS
	db VAPOREON, TCG_COLORLESS, TCG_COLORLESS
	db JOLTEON, TCG_COLORLESS, TCG_COLORLESS
	db FLAREON, TCG_COLORLESS, TCG_COLORLESS
	db ESPEON, TCG_COLORLESS, TCG_COLORLESS
	db UMBREON, TCG_COLORLESS, TCG_COLORLESS
	db LEAFEON, TCG_COLORLESS, TCG_COLORLESS
	db GLACEON, TCG_COLORLESS, TCG_COLORLESS
	db SYLVEON, TCG_COLORLESS, TCG_COLORLESS
	db PORYGON, TCG_COLORLESS, TCG_COLORLESS
	db PORYGON2, TCG_COLORLESS, TCG_COLORLESS
	db PORYGONZ, TCG_COLORLESS, TCG_COLORLESS
	db OMANYTE, TCG_COLORLESS, TCG_COLORLESS
	db OMASTAR, TCG_COLORLESS, TCG_COLORLESS
	db KABUTO, TCG_COLORLESS, TCG_COLORLESS
	db KABUTOPS, TCG_COLORLESS, TCG_COLORLESS
	db AERODACTYL, TCG_COLORLESS, TCG_COLORLESS
	db MARODACTYL, TCG_COLORLESS, TCG_COLORLESS
	db MUNCHLAX, TCG_COLORLESS, TCG_COLORLESS
	db SNORLAX, TCG_COLORLESS, TCG_COLORLESS
	db ARTICUNO, TCG_COLORLESS, TCG_COLORLESS
	db ZAPDOS, TCG_COLORLESS, TCG_COLORLESS
	db MOLTRES, TCG_COLORLESS, TCG_COLORLESS
	db DRATINI, TCG_COLORLESS, TCG_COLORLESS
	db DRAGONAIR, TCG_COLORLESS, TCG_COLORLESS
	db DRAGONITE, TCG_COLORLESS, TCG_COLORLESS
	db MDRAGONITE, TCG_COLORLESS, TCG_COLORLESS
	db ARM_MEWTWO, TCG_COLORLESS, TCG_COLORLESS
	db MEWTWO, TCG_COLORLESS, TCG_COLORLESS
	db MMEWTWOX, TCG_COLORLESS, TCG_COLORLESS
	db MMEWTWOY, TCG_COLORLESS, TCG_COLORLESS
	db MEW, TCG_COLORLESS, TCG_COLORLESS
	db MELTAN, TCG_COLORLESS, TCG_COLORLESS
	db MELMETAL, TCG_COLORLESS, TCG_COLORLESS
	db VENUSTOISE, TCG_COLORLESS, TCG_COLORLESS
	db THU_FI_ZER, TCG_COLORLESS, TCG_COLORLESS
	db MZYGARDE, TCG_COLORLESS, TCG_COLORLESS
	db UNECROZMA, TCG_COLORLESS, TCG_COLORLESS
	db MRAYQUAZA, TCG_COLORLESS, TCG_COLORLESS
	db EETERNATUS, TCG_COLORLESS, TCG_COLORLESS
	db ARCEUS, TCG_COLORLESS, TCG_COLORLESS
	db MISSINGNO, TCG_COLORLESS, TCG_COLORLESS
	db BLUESDAD, TCG_COLORLESS, TCG_COLORLESS
	db BLUESMOM, TCG_COLORLESS, TCG_COLORLESS
	db DAD, TCG_COLORLESS, TCG_COLORLESS
	db -1
