_TextTraveler_Intro::
	text "Salutations! I"
	line "would be pleased"
	cont "to introduce"
	cont "myself, but my"
	cont "name, of"
	cont "difficult"
	cont "pronunciation,"
	cont "holds no"
	cont "importance."

	para "You are invited"
	line "therefore to"
	cont "refer to me as"
	cont "TRAVELER, if so"
	cont "you wish."

	para "I come from a far"
	line "far far away"
	cont "land, dedicating"
	cont "my heart, mind,"
	cont "and body to my"
	cont "quest, which is"
	cont "to assemble the"
	cont "absolute"
	cont "strongest team of"
	cont "#MON ever"
	cont "witnessed by"
	cont "human eye."

	para "I am seeking a"
	line "specific certain"
	cont "creature, or any"
	cont "information"
	cont "pertaining it."
	cont "This creature is"
	cont "the #MON"
	cont "denominated"
	cont "MEGA MEWTWO."

	para "Would you mayhap"
	line "happen to possess"
	cont "one such"
	cont "specimen?"
	prompt

_TextTraveler_NoMMewtwo::
	text "Oh, you own no"
	line "control over"
	cont "MEGA MEWTWO!"
	cont "This is"
	cont "maximally"
	cont "unfortunate."

	para "I thank you for"
	line "your cooperation,"
	cont "and I salut you"
	cont "as I persist on"
	cont "my mission."
	done

_TextTraveler_YesMMewtwo::
	text "Oh! What"
	line "fortunate,"
	cont "marvelous"
	cont "serendipity! You"
	cont "indeed have"
	cont "control over a"
	cont "MEGA MEWTWO!"

	para "Please, I beseech"
	line "thee, let us"
	cont "engage in a"
	cont "battle as fair as"
	cont "humanly possible,"
	cont "as I possess the"
	cont "highest desire to"
	cont "test the battle"
	cont "prowess of this"
	cont "legendary"
	cont "creature, and"
	cont "judge with my"
	cont "very own eyes if"
	cont "it is worthy of"
	cont "belonging to my"
	cont "team!"
	done

_TextTraveler_DefeatPostBattle::
	text "Oh!!!"
	line "What an"
	cont "astonishing"
	cont "performance of"
	cont "wonder!"

	para "MEGA MEWTWO is"
	line "indeed as capable"
	cont "as my instruments"
	cont "and the rumors I"
	cont "collected hinted!"
	prompt

_TextTraveler_VictoryPostBattle::
	text "Oh..."
	line "I have to admit"
	cont "that the"
	cont "abilities of"
	cont "MEGA MEWTWO have"
	cont "appared somehow"
	cont "disappointing."

	para "Maybe this is not"
	line "the right reality"
	cont "for me to find"
	cont "completion to my"
	cont "quest...?"
	prompt

_TextTraveler_Compliments::
	text "You have my"
	line "deepest"
	cont "gratitude. This"
	cont "battle was indeed"
	cont "maximally"
	cont "insightful."

	para "I would thus"
	line "desire to narrate"
	cont "you the full"
	cont "extent of my"
	cont "story: when I"
	cont "claimed that I"
	cont "come from a far"
	cont "far far away"
	cont "land, I was not"
	cont "lying, but I was"
	cont "not even being as"
	cont "honest and"
	cont "thorough as I"
	cont "could have been."

	para "I, in fact, come"
	line "from another"
	cont "dimension"
	cont "altogether."

	para "I have been"
	line "traveling"
	cont "throughout"
	cont "universes to"
	cont "assemble the"
	cont "absolute"
	cont "strongest team in"
	cont "existence."

	para "I have collected"
	line "5 out 6 #MON,"
	cont "and my"
	cont "instruments"
	cont "suggested me to"
	cont "land in this"
	cont "dimension, as"
	cont "they picked up a"
	cont "terrific"
	cont "potential."

	para "And I was"
	line "disappointed not!"
	cont "I can now venture"
	cont "forth and catch"
	cont "this creature of"
	cont "might to finally"
	cont "complete the most"
	cont "powerful #MON"
	cont "team of the"
	cont "multiverse!!!"
	prompt

_TextTraveler_WhatWasThat::
	text "What... What was"
	line "that?!"

	para "Allow me to"
	line "verify... Oh!"
	cont "My instruments"
	cont "detected energy"
	cont "signatures"
	cont "identical to"
	cont "those of my 5"
	cont "#MON."

	para "It would indeed"
	line "seem that our"
	cont "almighty"
	cont "confrontation has"
	cont "ripped a rupture"
	cont "in the space-time"
	cont "matrix, and"
	cont "creatures"
	cont "equivalent to"
	cont "mines have been"
	cont "dragged into this"
	cont "dimension, where"
	cont "they belong not."

	para "They are most"
	line "definitely"
	cont "maximally filled"
	cont "with terror, and"
	cont "most likely they"
	cont "hid in the most"
	cont "remote location"
	cont "of this land..."

	para "You possess deeper"
	line "knowledge of"
	cont "these"
	cont "surroundings than"
	cont "I! I will hence"
	cont "entrust you with"
	cont "the duty of"
	cont "locating and"
	cont "soothe those"
	cont "creatures. I"
	cont "encourage you to"
	cont "try and catch"
	cont "them, as they"
	cont "would prove"
	cont "worthy addition"
	cont "to your team."

	para "Mind well that"
	line "they are"
	cont "literally unique"
	cont "in this"
	cont "dimension, so"
	cont "exercise extreme"
	cont "caution."

	para "In the meantime, I"
	line "will proceed in"
	cont "the completion of"
	cont "my mission."

	para "I wish you the"
	line "utmost of luck,"
	cont "and thank you"
	cont "again for your"
	cont "invaluable help!"

	para "...let me just add"
	line "one comment"
	cont "before leaving:"
	cont "with your power,"
	cont "you have what it"
	cont "takes to"
	cont "potentially be my"
	cont "most formidable"
	cont "opponent in the"
	cont "whole multiverse."
;	xxxx "123456789012345678"
	done
